### ISSUE TITLE
Finalize file names and URNS for the AP

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#1]
@cluckmarq and @amir-zeldes are discussing what system we should use for file names for the Apophthegmata Patrum, and is there any information we should be adding to the metadata?

**Comment by ctschroeder** [comment]
A summary of conversations btw @ctschroeder, @amir-zeldes, @cluckmarq so far:

Basic principles:
1. We want to have semantically meaningful file names
2. We want to have semantically meaningful permanent URNs
3. We are all in agreement about keeping the Chaine #s in the filenames and probably permanent URNs
4. After Chaine numbering, we will identify the sayings by their corresponding Greek siglum if one exists:
  a. [Regnault](https://www.zotero.org/groups/coptic_scriptorium/items/itemKey/ZC5ND2QC)'s charts pp. 200 and following are the first stop for determining if there is a Greek parallel; if no parallel in [Regnault](https://www.zotero.org/groups/coptic_scriptorium/items/itemKey/ZC5ND2QC), consult with @cluckmarq.  
  b. Sayings with parallels in the Alphabetical collection will be named with Chaine # followed by the name of the affiliated abba/amma *as designated in the Greek Alphabetical collection* and the number of that saying (as two digits) *as designated in the Greek Alphabetical collection*.  For names with descriptors (e.g., Isaac of the Cells), try to reduce the name to two words with underscore (e.g., Isaac_Cells)
  c. Sayings with parallels in the anonymous collection are named with Chaine # followed by the Nau numbers (N###) followed by a word designating a theme (e.g., eucharist, prayer). 
5. Metadata should contain Chaine and known Greek parallels

Examples:
AP.022.isaac_cells.08
AP.026.cassian.07
AP.192.n068.eucharist
AP.216.bessarion.01
AP.217.bessarion.02

How does this look?  Capitals or no capitals?  I removed them here.  Please revise as needed.  Thanks!

**Comment by amir-zeldes** [comment]
Looks good to me. I’m fine with all lower case, and I think the only alternative is all upper or camel case, because otherwise it’s hard to predict if _Cells in Isaac of the Cells will be capitalized or not. All lower solves that and maybe looks less jarring in URLs.

**Comment by ctschroeder** [comment]
Sounds good.  @0restes:  please read through this and keep these principles in mind for the AP corpus URNs.  Check with me when you get working on that corpus.  It is tricky, and Bridget and I didn't really work through final models for that corpus.

**Comment by 0restes** [comment]
Okay, that all sounds great--thanks, Carrie.  In order to extend the longevity of the resolver service, we've spoken about making some amount of these fields editable via the superuser managing the ingest/release, so if they need to change in the future, it won't be a problem.

**Comment by ctschroeder** [comment]
Summarizing and editing here re filenames after consultation with @cluckmarq about naming apophthegms with no Greek parallels.  URNs are still a bit of an issue:

Basic principles:

1. We want to have semantically meaningful file names

2. We want to have semantically meaningful permanent URNs

3. We are all in agreement about keeping the Chaine #s in the filenames and probably permanent URNs

4. After Chaine numbering, we will identify the sayings by their corresponding Greek siglum if one exists:
  a. [Regnault](https://www.zotero.org/groups/coptic_scriptorium/items/itemKey/ZC5ND2QC)'s charts pp. 200 and following are the first stop for determining if there is a Greek parallel; if no parallel in [Regnault](https://www.zotero.org/groups/coptic_scriptorium/items/itemKey/ZC5ND2QC), use "unid" in the filename (for unidentified) + a name or thematic word to give it semantic meaning (e.g. ap.005.unid.senses)
 b. Sayings with parallels in the Alphabetical collection will be named with Chaine # followed by the name of the affiliated abba/amma *as designated in the Greek Alphabetical collection* and the number of that saying (as two digits) *as designated in the Greek Alphabetical collection*.  For names with descriptors (e.g., Isaac of the Cells), try to reduce the name to two words with underscore (e.g., Isaac_Cells)
  c. Sayings with parallels in the anonymous collection are named with Chaine # followed by the Nau numbers (N###) followed by a word designating a theme (e.g., eucharist, prayer). 
5. Metadata should contain Chaine and known Greek parallels

Examples:
ap.005.unid.senses
ap.022.isaac-cells.08
ap.026.cassian.07
ap.192.n068.eucharist
ap.216.bessarion.01
ap.217.bessarion.02
