### ISSUE TITLE
Loading modal for interactions with search tools and text navigation

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#10]

**Comment by lukehollis** [comment]
Now a user sees the loading modal and spinner while waiting:
![loading](https://cloud.githubusercontent.com/assets/2633382/6762733/5dd18360-cf3c-11e4-82d8-5ce76db3d5d4.png)

**Comment by ctschroeder** [comment]
Yes we do!  Still seems slow on first load but that is not this issue, so closing.
