### ISSUE TITLE
Streamline functionality to improve performance

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#101]
@amir-zeldes and @ctschroeder noticed site is sometimes slow to load document list.  @dcbriccetti noticed a lot of database calls happening each time the system is used.  It would be desirable to improve performance to make the site work smoother, faster.  @dcbriccetti will keep an eye on the issue while fixing other things and consider possible strategies for improving performance.  We will check in in a month or so.

**Comment by ctschroeder** [comment]
See also https://github.com/CopticScriptorium/cts/issues/95

**Comment by ctschroeder** [comment]
Third instance (what will be the new production instance) set up on AWS with 4 GB RAM, 2 vCPUs, 8 GB storage.

**Comment by dcbriccetti** [comment]
I’ve done quite a bit of work here. We should be noticing improvements. More can be done.

**Comment by dcbriccetti** [comment]
Try now: http://52.39.198.200/

**Comment by amir-zeldes** [comment]
Performance now is fast enough that a progress bar / spinner is truly superfluous. The only confusing case is when there are no results, since there is no "no results" message, and no spinner indicating that the search got carried out. I'll make an issue for adding explicit "no results".

**Comment by ctschroeder** [comment]
OH WOW THIS IS AMAZING!!!  Thank you!!!!!!!
