### ISSUE TITLE
Add no results message

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/cts#103]
If filters are chosen that, together, match no results, there should be an informative message that there are no results.

**Comment by dcbriccetti** [comment]
Something like this?

<img width="809" alt="screen shot 2016-05-27 at 1 54 51 pm" src="https://cloud.githubusercontent.com/assets/55099/15620997/b8c26664-2412-11e6-81d7-09b1cb8e33bd.png">

**Comment by amir-zeldes** [comment]
Perfect - or even better: "There are no results matching your search"

**Comment by dcbriccetti** [comment]
Will go to test server in text batch.
