### ISSUE TITLE
URL links not working properly

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#106]
There's something wrong with the standardized web links to visualizations in the reference section.  E.g., http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.fox.monbxh_204_216/analytic/html doesn't work.

**Comment by dcbriccetti** [comment]
I clicked on this link:
<img width="862" alt="screen shot 2016-10-20 at 2 27 25 pm" src="https://cloud.githubusercontent.com/assets/55099/19578641/7abdbfe4-96d1-11e6-8e91-cda0a59c5900.png">
And got this:
<img width="752" alt="screen shot 2016-10-20 at 2 27 43 pm" src="https://cloud.githubusercontent.com/assets/55099/19578646/80559f3a-96d1-11e6-9cbf-60ac4ddfe839.png">

Is that not correct? (Forgive me if it obviously isn’t. It’s been a while.

**Comment by ctschroeder** [comment]
That's correct.  Hang on, let me click around.  It wasn't working earlier.

**Comment by ctschroeder** [comment]
Ok, it looks like I may have been mistaken. There is a delay, and while delayed, the main index page is displayed. For big documents, it's long (well, long by web standards).  See for example http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.eagerness.monbxj_77_86/norm/html or http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.eagerness.monbxj_77_86/dipl/html .  Was there not a delay for you?

**Comment by ctschroeder** [comment]
I suspect logged this issue when I was trying to access a large document.  I saw the index page, instead.  I don't think the delay needs to (can?) be fixed, but is there a way to indicate the page is coming.  Bringing back the little spinning circle, or defaulting to something else while it loads?

**Comment by dcbriccetti** [comment]
Two seconds for the first, 1 second for the second.
As I recall, there is some inefficiency in the coordination between what Django emits and what AngularJS does.
My hunch—again, been away for awhile—is that speeding this up would not be a simple change.

**Comment by ctschroeder** [comment]
We just commented at the same time.  Agreed on not trying to fix the speed issue.  Is there something else easy, so no one thinks it's broken (instead of loading)?

**Comment by dcbriccetti** [comment]
Later tonight or tomorrow I’ll take a look.

**Comment by ctschroeder** [comment]
Thank you. I want to be sure people don't think the feature is broken. I think my delay was a bit longer than yours, so that may be the case for others.

**Comment by ctschroeder** [comment]
No, it's correct.  For some reason it wasn't working earlier.  Let me 
click around a bit.  Hang on.

**Comment by dcbriccetti** [comment]
I’ve been doing some logging and tracing through the JavaScript code, and have found nothing to explain that delay. Chrome Developer Tools simply says “Layout”.

![screen shot 2016-11-16 at 1 36 38 pm](https://cloud.githubusercontent.com/assets/55099/20366879/e657276e-ac01-11e6-9cc5-8278762093d7.png)


I tried the same sequence in Safari, and there’s **no** delay. Do you see the same?
