### ISSUE TITLE
Order documents according to "order" metadatum field

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#107]
We are rolling in slowly a new metadatum field, "order."  Documents in this application should be listed in order of the number contained in the metadatum field "order."  This field is optional.  If the field doesn't exist or is blank, you can list the documents alphabetically.  (We are *trying* to make sure that all docs in a corpus will have this field.)

**Comment by dcbriccetti** [comment]
This is coded and tested but not yet deployed.

**Comment by dcbriccetti** [comment]
This is implemented on the test system now.
