### ISSUE TITLE
Timeout when application retrieves large viz documents during ingest

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#108]
During an ingest, the application seems to timeout on large documents.  We noticed that some visualizations in the corpus I See Your Eagerness were missing.  We've ingested several times, checking the documents in the corpus I See Your Eagerness each time.  There are different document visualizations missing each time, but they always are visualizations of the larger files. 

We think that the app is timing out during the ingestion process.  We think this is in the selenium code.  @amir-zeldes says there are a few solutions, if this is the case:  increase the time before a timeout, or create a more responsive mechanism that communicates that the ingestion of a doc/viz is complete.  Please check in with us about the options.

**Comment by dcbriccetti** [comment]
I am able to reproduce this. The timeout value was two minutes. I am seeing if increasing it stops the problem.

**Comment by dcbriccetti** [comment]
After increasing the timeout to ten minutes, a 502 error appeared in the browser on my development system after a few minutes, and then appeared in the log after the ten minutes passed. Is this a problem with ANNIS?
```
2016-12-11 23:23:40,186 INFO    vis     Fetching 3 visualizations
2016-12-11 23:23:40,186 INFO    vis     Normalized Text
2016-12-11 23:33:42,011 ERROR   vis     Error getting https://corpling.uis.georgetown.edu/annis/embeddedvis/htmldoc/shenoute.eagerness/GF17-18?config=norm: Message: 

2016-12-11 23:33:42,019 ERROR   vis     Page source: <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=11;chrome=1" />
  <style type="text/css">html, body {height:100%;margin:0;}</style>
  <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="./../../../VAADIN/themes/annis_embeddedvis/favicon.ico" />
  <link rel="icon" type="image/vnd.microsoft.icon" href="./../../../VAADIN/themes/annis_embeddedvis/favicon.ico" />
 <link rel="stylesheet" type="text/css" href="./../../../VAADIN/themes/annis_embeddedvis/styles.css?v=7.7.3" /><script type="text/javascript" src="./../../../VAADIN/widgetsets/annis.gui.widgets.gwt.AnnisWidgetSet/annis
.gui.widgets.gwt.AnnisWidgetSet.nocache.js?1481498620736"></script><link rel="stylesheet" href="https://corpling.uis.georgetown.edu/annis/VAADIN/widgetsets/annis.gui.widgets.gwt.AnnisWidgetSet/popupbutton/popupbutton.c
ss" /><link rel="stylesheet" href="https://corpling.uis.georgetown.edu/annis/VAADIN/widgetsets/annis.gui.widgets.gwt.AnnisWidgetSet/anniswidget/styles.css" /><script src="https://corpling.uis.georgetown.edu/annis/VAADI
N/widgetsets/annis.gui.widgets.gwt.AnnisWidgetSet/062DF9A34C17F11E692AB31C248F6757.cache.js"></script></head>
 <body scroll="auto" class="v-generated-body v-sa v-ch v-webkit v-mac">
  <div id="annis-92967627" class="v-app annis_embeddedvis embeddedvisui" style="overflow: auto;">

<title>502 Proxy Error</title>

<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/annis/embeddedvis/htmldoc/shenoute.eagerness/GF17-18">POST /annis/embeddedvis/htmldoc/shenoute.eagerness/GF17-18</a></em>.</p><p>
Reason: <strong>Error reading from remote server</strong></p><p></p>
<hr />
<address>Apache/2.2.15 (Red Hat) Server at corpling.uis.georgetown.edu Port 443</address>

</div>
  <script type="text/javascript" src="./../../../VAADIN/vaadinPush.js?v=7.7.3"></script>
  <script type="text/javascript" src="./../../../VAADIN/vaadinBootstrap.js?v=7.7.3"></script>
  <script type="text/javascript">//&lt;![CDATA[
if (!window.vaadin) alert("Failed to load the bootstrap javascript: ./../../../VAADIN/vaadinBootstrap.js?v=7.7.3");
vaadin.initApplication("annis-92967627",{"theme":"annis_embeddedvis","versionInfo":{"vaadinVersion":"7.7.3","atmosphereVersion":"2.2.9.vaadin2"},"widgetset":"annis.gui.widgets.gwt.AnnisWidgetSet","widgetsetReady":true,
"comErrMsg":{"caption":"Communication problem","message":"Take note of any unsaved data, and &lt;u&gt;click here&lt;/u&gt; or press ESC to continue.","url":null},"authErrMsg":{"caption":"Authentication problem","messag
e":"Take note of any unsaved data, and &lt;u&gt;click here&lt;/u&gt; or press ESC to continue.","url":null},"sessExpMsg":{"caption":"Session Expired","message":"Take note of any unsaved data, and &lt;u&gt;click here&lt
;/u&gt; or press ESC key to continue.","url":null},"vaadinDir":"./../../../VAADIN/","standalone":true,"heartbeatInterval":30,"serviceUrl":"./../../.."});
//]]&gt;</script>
 
<iframe src='javascript:""' id="annis.gui.widgets.gwt.AnnisWidgetSet" tabindex="-1" style="position: absolute; width: 0px; height: 0px; border: none; left: -1000px; top: -1000px;"></iframe></body></html>
```

**Comment by amir-zeldes** [comment]
Well, I'm not sure this is an ANNIS problem. Is the error always on this particular document? I don't see anything very unusual with it. In fact, there's no problem loading the embedded visualization link that it complains is unavailable:

https://corpling.uis.georgetown.edu/annis/embeddedvis/htmldoc/shenoute.eagerness/GF17-18?config=norm

The only thing I notice is one spot that has the dictionary hyperlink formatting show up without hover. This seems to be the result of a "note" annotation being applied in the middle of a word group. But that's not really a 'deal breaker' for ANNIS, it just looks a little odd. And since the HTML page at the link above does actually load without incident, shouldn't the repo code just fetch whatever it rendered?

Please let me know if it's always the same document (suggests an ANNIS problem) or varies (some other sort of communication problem or a bug in the repo code?)

**Comment by dcbriccetti** [comment]
I may have a reliable workaround: creating a new headless browser for each request, and retrying failing requests. With this new code, I made two ingestion runs for the same two corpora, logging the number of retries required and the fetch timings for each visualization. The corpus/text/vis’es requiring retries were different between the two runs. See below for details. A longterm solution would be to add a simpler way to get the visualizations from ANNIS (as we’ve discussed).

[vis-fetches.pdf](https://github.com/CopticScriptorium/cts/files/645230/vis-fetches.pdf)
[vis-fetches.xlsx](https://github.com/CopticScriptorium/cts/files/645231/vis-fetches.xlsx)

**Comment by amir-zeldes** [comment]
Well, variation in the time is to be expected, but I'm not sure why we're seeing timeouts. Retrying failed requests seems sensible to me. Does re-creating the browser make the ingestion substantially slower or is this more or less negligible? 

I'm not sure what would be a simpler way to get the visualizations, except making the embed live (but then users on the repo might run into timeouts and have to deal with latencies, which is what we're trying to avoid).

**Comment by dcbriccetti** [comment]
Re-creating the browser slows the process a bit. I haven’t measured it. < 5% per request would be my guess. Without it, I wasn’t able to get the retries to work without a five-minute hang.

I was thinking of ANNIS having a simpler web service that didn’t require a browser.

Shall I implement this on the test system so you can try it out?

**Comment by ctschroeder** [comment]
It's fine with me to put it on the test system.  It is hard for me to 
tell how long the ingestion process takes from the admin interface.  I 
generally start it and come back in a half an hour (if it's a smaller 
corpus) or an hour (in a larger one) and hope no one else is online at 
the time.  I know accessing the system during an ingestion can sometimes 
mess it up.

Also:  if there is an easier way to access ANNIS (without a browser) 
it's fine to look at that. BUT we don't right now have a budget for an 
extensive intervention, if an alternative to re-creating the browser 
looks like a long project.

**Comment by dcbriccetti** [comment]
Simplifying getting the visualizations from ANNIS would require a new feature be added to ANNIS, and a couple hours on our side. So that’s sort of a wish for the future.

**Comment by ctschroeder** [comment]
Thanks for the reminder.

**Comment by amir-zeldes** [comment]
Oh, yes, now I understand what you mean. The metadata comes from the ANNIS service, so that's an example that doesn't go over a browser. Sadly, the entire code that generates the HTML visualizations is part of the front-end, which is a Tomcat webapp based on VAADIN. It's not really possible to port this code to the service without a substantial effort, so this is probably not something we'll be doing anytime soon I'm afraid.

**Comment by dcbriccetti** [comment]
The more robust visualization fetching is in place on the test system, http://52.39.198.200/.
Also, you can watch the progress of ingestions here now: http://52.39.198.200/admin/ingest/ingest/. Reload the page and you can see how many texts and corpora have been ingested. There’s no longer a long-running search rebuild at the end, so once “Num Corpora Ingested” reaches the number you selected, the ingestion is done. You’ll still need to look at the log if there are problems. Once you ssh in, you can use lnav like this, if you like:
`lnav /var/www/cts/coptic/django_logger.log`

**Comment by amir-zeldes** [comment]
That's a great feature, thanks, I'll test when I get a chance. Meanwhile, it looks like the combination of ingestions and students working on final papers caused ANNIS to crash. I think ultimately we should look into a separate ANNIS server for the Coptic data.

**Comment by ctschroeder** [comment]
I tried ingesting Besa and ISYE this morning on the test server.  The 
process was quick -- thanks for the progress notification!!  The 
document ordering works in the Besa corpus, Amir.  (We haven't added the 
metadata to any other corpus yet.)  All the visualizations seem to have 
been ingested for ISYE.  I tested the large documents, and they all 
appeared. Thank you Dave!!

The only catch was that there was sometimes a delay, either in 
generating the whole page or in generating the visualization.  For some, 
the metadata would appear and then a moment or two later the 
visualization. The AWS instance for the test server is smaller than the 
one for our production server.  It's possible the delay won't be as 
pronounced.

We are bumping up against our budget limit for these fixes, so I think 
if there is not an obvious way to mitigate against the delay I just 
described, we should deploy on the production server and congratulate 
ourselves on a job well done.

Amir: Feel free to email me about putting Coptic on a separate ANNIS 
server.  As far as I know, no one is conducting research on your other 
corpora + Coptic except perhaps you.  The only problem I see is the 
issue is stability of links to queries.

**Comment by dcbriccetti** [comment]
There’s nothing quick I can do about the delay, and I don’t think it should be any better on the production system.

**Comment by ctschroeder** [comment]
So we deal with it?

**Comment by amir-zeldes** [comment]
Yes, I think until we have more budget to deal with it, it's not a huge issue (ingest is a fairly rare event). I would like to explore a Coptic ANNIS server, but maybe a little down the road.
