### ISSUE TITLE
Make menu bar pull dynamically from common source

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#109]
The goal is to make the menu/nav bar pull dynamically from the same source as the tools and pages.
@amir-zeldes notes a possible approach can be found here:
http://stackoverflow.com/questions/7333843/django-include-external-include-files
One would need to register a new template tag with the Django app, which means some less local changes.

**Comment by amir-zeldes** [comment]
I think this is resolved via e7f0a932b75bbbfb0aaba9c8536b18af7ee4140b and f18b41c1dca3d7f5ddddf2caecbf0ef1f488ba70

Note that we decided to buffer CTS from the live menu, meaning the menu is only re-generated by running coptic/nav.py - it is then dynamically fetched from copticscriptorium.org and persisted to the repo server.
