### ISSUE TITLE
Capitalization visualization issue

### ISSUE THREAD

**Issue by eplatte** [CopticScriptorium/cts#110]
Corpus names are still visualizing as capitalized not in the menu (which Amir fixed a few weeks ago), but on the display next to the word filter at the top of the page

**Comment by ctschroeder** [comment]
I confess I don't entirely understand this issue. Is it still a live problem? If so, could you add a screenshot to clarify @eplatte? Is this low priority? Thanks.

**Comment by eplatte** [comment]
Yes, this is still an issue. I think it's low priority, but it would be good to have it fixed to avoid confusion.
<img width="960" alt="capitalization_screenshot" src="https://user-images.githubusercontent.com/8419381/32234148-4b5f41bc-be19-11e7-8e2d-4326bd95bc86.png">

**Comment by ctschroeder** [comment]
this was fixed
