### ISSUE TITLE
Add mechanism to redirect obsolete URNs

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#112]
Add deprecated URNs with fresh links to the search error result in the base.html file.  (coptic OT to GitHub + new corpora, Shenoute A22 and AOF)

**Comment by amir-zeldes** [comment]
Leaving this open as a reminder to handle missing URNs better.

**Comment by amir-zeldes** [comment]
We need a mechanism to handle obsolete/moved URNs - currently a hard wired message in the template gives a first response to any missing URN.

**Comment by lgessler** [comment]
This should be pretty straightforward. Is there a list of pairs of old-new URNs anywhere?

**Comment by ctschroeder** [comment]
Hi! I know I created a csv file but now can't find it anywhere. However, I did list them on the old index file (see here https://github.com/CopticScriptorium/cts/commit/bb8dfcdc78670215cd477bb6caacae80341cf676), and there should be document level metadatum called document_cts_urn_deprecated that exists only in these files.  Is this enough information to go on? If not, please let me know.
There are not many files, just a few old ones from when we were still figuring a number of things out.
Thanks so much!

**Comment by amir-zeldes** [comment]
We can definitely figure out the list based on that information, and extend it in the future if it turns out we forgot something. The main question would be where to configure this - a csv file on the server? Or expose it somehow in the grappelli admin interface?

**Comment by ctschroeder** [comment]
I found the file: 
[urn-table.xlsx](https://github.com/CopticScriptorium/cts/files/3742342/urn-table.xlsx)

**Comment by ctschroeder** [comment]
Hi. Can this be implemented soon? Is there anything else I can do to help? Thank you so much!

**Comment by lgessler** [comment]
I'll get to this and #122 once my semester's over. Should be in time for Christmas :)

**Comment by ctschroeder** [comment]
Fabulous. Thank you. Good luck with your end of semester work!

**Comment by lgessler** [comment]
@ctschroeder can you explain your note on the last pattern? You wrote:

> `urn:cts:copticLit:ot.*.crosswire` should direct people to GitHub, but since the corpus is still called sahidic.ot we should either direct to the last version of the release (https://github.com/CopticScriptorium/corpora/releases/tag/v2.5.0 ) or make a new folder. I vote for last version of the release.

I think this means any URN matching `urn:cts:copticLit:ot.*.crosswire` should redirect to https://github.com/CopticScriptorium/corpora/tree/master/sahidic.ot. Is that right?

**Comment by ctschroeder** [comment]
> I think this means any URN matching urn:cts:copticLit:ot.*.crosswire should redirect to https://github.com/CopticScriptorium/corpora/tree/master/sahidic.ot. Is that right?
> 
Please redirect to https://github.com/CopticScriptorium/corpora/releases/tag/v2.5.0

That’s the last release in which we used the Crosswire data. All the later OT data is from another source.

**Comment by lgessler** [comment]
OK, fixed in #123 and deployed. Let me know if there's anything else!

**Comment by amir-zeldes** [comment]
Thanks Luke - I tried a couple of these in production, but I can't get it to work - it just says:

`No results found for urn:cts:copticLit:shenoute.abraham.monbya_547_550 in any field.`

I just tried putting things like "urn:cts:copticLit:shenoute.abraham.monbya_547_550" in the box, or "urn:cts:copticLit:ot.gen.crosswire:3" / "urn:cts:copticLit:ot.gen.crosswire". Did I misunderstand something?

**Comment by lgessler** [comment]
What URLs are you typing in, exactly? The links [data.copticscriptorium.org/urn:cts:copticLit:ot.gen.crosswire:3]() and [data.copticscriptorium.org/urn:cts:copticLit:shenoute.abraham.monbya_547_550]() are working for me.

**Comment by lgessler** [comment]
Oh, you're using the box! Forgot to handle that

**Comment by lgessler** [comment]
OK, fixed in #124

**Comment by amir-zeldes** [comment]
Fantastic, thanks!

**Comment by ctschroeder** [comment]
I've just had a chance to check this, and the urns in the box all work. Thanks!
