### ISSUE TITLE
Update data.copticscriptorium style/look

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#113]
Pull new design files into main installation, change main text font to slightly darker hue (@amir-zeldes demo'd this live in DC using his browser inspector or some such)

**Comment by ctschroeder** [comment]
Hi, @amir-zeldes. Would it be possible for you to check on this when also looking at https://github.com/CopticScriptorium/cts/pull/114?  Many thanks!  We are SOOOO CLOSE.

**Comment by ctschroeder** [comment]
We were also going to change that menu bar color -- to the same red used elswhere, I think.  (Another option is black.)

**Comment by amir-zeldes** [comment]
OK, deployed!
