### ISSUE TITLE
Ensure URL and URN links to HTML Versions toggle the selected HTML Version's visibility

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#12]

**Comment by lukehollis** [comment]
When a user visits this URN: http://coptic.aweb.io/urn:cts:copticLit:shenoute.A22:MONB.YA:ya421-428/dipl/html
or navigates to this link: http://coptic.aweb.io/texts/ya421-428/dipl
they will see the diplomatic HTML version shown. (Compare to the default http://coptic.aweb.io/texts/ya421-428/)

**Comment by ctschroeder** [comment]
http://coptic.aweb.io/urn:cts:copticLit:shenoute.A22:MONB.YA:ya421-428/dipl/html is a path not a cts URN.  The link doesn't resolve properly either.  Just takes you to the splash page.

**Comment by lukehollis** [comment]
Looks like that's an outdated URN in this path.  Here's the equivalent in the updated path: http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.a22.monbya_421_428/dipl/html
