### ISSUE TITLE
Add support in the Angular router for the Text Navigation, selected search fields, and collections

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#13]

**Comment by lukehollis** [comment]
Now the client side application handles most of the logic of routing and search tools: per routes.js here https://github.com/CopticScriptorium/cts/blob/master/coptic/client/routes.js

**Comment by ctschroeder** [comment]
?

**Comment by lukehollis** [comment]
A user can now select search tools and browse to documents without a page refresh.  The Angular client-side application handles all of this now.
