### ISSUE TITLE
Consider methods of flagging facet to be included as SearchField from ANNIS metadata API query

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#14]

**Comment by amir-zeldes** [comment]
In addition to the flagging parameter it might be useful to have an ordering parameter in the same place (if it's a tabular data model), as well as an optional 'display name' (defaults to the metadatum itself, but sometimes it might be nice if a cryptic TEI-like name is displayed as something more human friendly in the nav bar).

**Comment by lukehollis** [comment]
From our emails:  top N displayed in search toolbar and remainder in adv. search dropdown, each search field has a priority/order integer, search fields with negative priority are not displayed.  Having a configurable display name to partner with an internal slug/identifier sounds good also!

**Comment by lukehollis** [comment]
All I need here is to know what this will look like in the XML coming from ANNIS, and I'll be able to implement a fix for this in the Ingest modules.

**Comment by amir-zeldes** [comment]
My plan was not to have it look special in any way in ANNIS, but to configure these things in the admin part of the URN site component (part of the configuration). ANNIS is a generic search tool being developed for all sorts of corpora, so it’s not really designed with this specific website as a client in mind. There are some attributes that metadata can be given (primarily namespaces), but I’d rather not abuse those for this purpose. Is there any reason not to make the facetting behavior part of the website configuration?

**Comment by lukehollis** [comment]
Nope, no need to have this in ANNIS--an administrator can easily remove these from the admin backend. Whatever your preference is sounds good to me!

**Comment by lukehollis** [comment]
Since we're administering this manually in the URN resolver, this ticket can be closed.

**Comment by ctschroeder** [comment]
This issue is reopened because there was a misunderstanding.  When Luke said there was no need to put the configurations in the ANNIS metadata, I did not read that as meaning the configurations in the resolver would have to be manually reset at every single ingest.  Manual was clear, but the question was also about configuring at every ingest.

**Comment by amir-zeldes** [comment]
I still don't think we want to add ANNIS metadata with the sole function of feeding the repo as a hack - these corpora will have the same metadata in the export formats which have nothing to do with the repo, and it's not really a detail about our data, it's about this particular repo. I'm happy enough configuring them manually once in the Django interface, but once a new ingest comes in they shouldn't be overwritten - I think it should set a blank priority field etc. only for corpus+metadatum combinations it hasn't seen before (so append only, no overwrite).

**Comment by ctschroeder** [comment]
@amir-zeldes can this be closed?

**Comment by amir-zeldes** [comment]
Yeah, the way the Django/Grappelli UI works right now makes this superfluous. We could use namespaces in the future if we want the repo to ignore some metadata, actually. Closing.
