### ISSUE TITLE
Add site branding and colors from visual work done for CopticScriptorium.org

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#15]
(kept CopticScritorium.org palette, just desaturated a bit for reading)

**Comment by lukehollis** [comment]
Will have to do a hard refresh (or visit http://coptic.aweb.io/static/img/favicon.ico) to see favicon

**Comment by lukehollis** [comment]
Use favicon with manuscript background, use asul font, use original colors without being desaturated, add full logo instead of partial

**Comment by lukehollis** [comment]
Add footer content and sponsor logos

**Comment by lukehollis** [comment]
Okay, updated colors, branding and layout.  Will have to fix up responsive styles, but this should get the branding moving in the right direction regarding our most recent Skype call.

**Comment by lukehollis** [comment]
P.S. May need to do a refresh to see updates, esp. for favicon.

**Comment by ctschroeder** [comment]
Oh here is the ticket -- see my comments here.  https://github.com/CopticScriptorium/cts/issues/39
Thanks for the efforts!  Some  of it looks really good, but some of it ended up not quite right.  I have some suggestions in the other thread.

**Comment by ctschroeder** [comment]
Also see my email re the footer: The footer content is not quite the same (namely, the license). Can you make the content the same?  I have added an issue to github about licensing of *your* code.  Everything else is cc-by.  We neglected to add it to our footer until today.  Your copyright notice reminded me!  We are using open culture/open source licenses as much as possible.  
If there is some way for your footer script to call our footer content, that would be great -- then we don't have to redo yours when we redo ours.  (this is in email)

**Comment by lukehollis** [comment]
Thanks for all the specific feedback!  I'm making sure I don't lose any of it by relisting items from the email here: 

-please add our floating nav bar to the top or put a link to the main
page-- we will add a link to the urn resolver on our nav bar, as well,
when we are done
-put the URN box back on the right where it was before [or on the far
right of your menu bar]. that had a very clean look
-you can keep our banner on the top with the manuscript image in the
background or you can just use the banner logo w/ white background but
please get rid of the manuscript image for the rest of the page.  If you
want to make it look like our other pages, that background image is
brightened substantially -- see our css
https://github.com/CopticScriptorium/CopticScriptorium.github.io/blob/master/scriptorium.css
with     background-color: hsla(40,53%,100%,0.80);  The ms image has an
80% brightness on our homepage for the content box.  Given the format
you have here with the rows I recommend eliminating it or fading it out
dramatically in the background of the content area.
-For now keep the font and the brown background for the menu-- that
looks good
-footer:  I am making a ticket about licensing *your* code.  In the
meantime, could you please make the footer look exactly like our main
site footer (including the licensing instead of copyright); yours looks
good, and I think the main thing is needing to change the copyright. We
neglected to add our cc-by license it to our footer until today.  Your
copyright notice reminded me!  We are using open culture/open source
licenses as much as possible.  if there is some way for your footer
script to call our footer content, that would be great -- then we don't
have to redo yours when we redo ours.

**Comment by ctschroeder** [comment]
Ok. Sounds good. Please also check the mobile layout. I notice copticscriptorium.org resizes the banner, etc, for mobile layout. The one in this site does not resize and so takes up a ton of screen space. Thank you!

carrie@carrieschroeder.com

**Comment by lukehollis** [comment]
Okay, I've updated these items:

- [x] Added floating nav bar
- [x] Put urn box back to the right
- [x] Removed parchment background for body; parchment color in header is the same color as the parchment color on the copticscriptorium.org site--the background-color with an 80% opacity is being set to the #content element on the copticscriptorium site.  Where possible, I used the copticscriptorium styles directly to help things look consistent.
- [x] Updated footer content--currently, there's not a great way to pull the copticscriptorium.org footer content directly, but I'll keep thinking about this.  

Let me know your thoughts, and if everything looks good, I'll update the responsive styles so that the site looks good on tablets/mobile devices.  

Thanks!

**Comment by ctschroeder** [comment]
Much better, thanks.  Still not quite right with the header on mobile but much better, thanks!  See screen shots below for examples:
What it looks like:



What our site looks like and this should look like solely in terms of the banner:

**Comment by lukehollis** [comment]
Okay, I've updated the responsive styles to make everything look good on smaller browsers.  This ticket should be ready to close.

**Comment by ctschroeder** [comment]
Yay! Last two things: the visited links in the footer are the wrong color, and we need to add the Apache license somewhere, probably in the footer. Tell me if I should add it to our main footer or if you will add it here.

carrie@carrieschroeder.com

**Comment by lukehollis** [comment]
Okay, sounds good--update the visited color and added the apache license link and text.  Let me know your thoughts.

**Comment by ctschroeder** [comment]
Looks good--please close!  Hurray!

carrie@carrieschroeder.com

**Comment by lukehollis** [comment]
Sounds good! Closing.
