### ISSUE TITLE
Add metadata and information about text for default after selecting text title

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#18]

**Comment by ctschroeder** [comment]
I am not sure what this ticket is about.  If it is about the Information section that used to pop up for each document:  it looks like that Information section is now gone.  (It used to be populated with metadata from ANNIS on the corpus level, which I noted was not quite appropriate; I believe I suggested changing to document level metadata or hiding.  Document level metadata is preferred.)

**Comment by lukehollis** [comment]
Ref to this issue https://github.com/CopticScriptorium/cts/issues/52 for the document ANNIS metadata.

**Comment by ctschroeder** [comment]
looks like this is working
