### ISSUE TITLE
Query and Ingest Docname list for each corpus in ANNIS

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#19]

**Comment by lukehollis** [comment]
@amir-zeldes, I've looked back through our emails searching for the API query to ANNIS to retrieve a list of docnames for each corpus and haven't been able to find it.  When you have a second, can you send this my way?

**Comment by amir-zeldes** [comment]
Sure, it’s:

 

http://corpling.uis.georgetown.edu/annis-service/annis/meta/docnames/besa.letters

 

etc.

**Comment by lukehollis** [comment]
Awesome, thanks so much!

**Comment by lukehollis** [comment]
Okay, updated the docname ingest and everything's behaving as expected.  Just waiting on the new ingest to finish now.

**Comment by lukehollis** [comment]
All of the docnames are generated dynamically from the ingest for each corpus from ANNIS.  This ticket is ready to close.

**Comment by ctschroeder** [comment]
where do I go to see if this is functioning?

Also is the name for Letter to Aphthonia on the doc list supposed to be Letter or Letters?  Right now it is Letters -- I don't think this is coming directly from ANNIS, is it?

**Comment by lukehollis** [comment]
Hi Carrie, the docnames are ingested here in the ingest logic,  https://github.com/CopticScriptorium/cts/blob/master/coptic/ingest/ingest.py#L43, and all the docnames of the documents ingested are generated by the ingest from ANNIS, so all of these on the front of end of the site are evidence of this working.

**Comment by ctschroeder** [comment]
Thanks. sounds good. We are going to be changing some docnames, but since they are generated by the ingest from ANNIS, that shouldn't be a problem, right? They will get renamed. (We need to be sure the canonical CTS URNs don't change, though.)

**Comment by lukehollis** [comment]
Yes, that's correct--whatever ANNIS has them listed as, the resolver will ingest, so they'll be renamed on the ingest.
