### ISSUE TITLE
Ingest SearchFields and Values from ANNIS API

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#2]

**Comment by lukehollis** [comment]
Complete, with the caveat from ticket https://github.com/CopticScriptorium/cts/issues/22 that splittable params and SearchFieldValues have to be configured manually.

**Comment by lukehollis** [comment]
All the search fields and values are ingested directly as-is from ANNIS API: 
![searchfields](https://cloud.githubusercontent.com/assets/2633382/6762824/bfbdf0a8-cf3d-11e4-89e1-f7b743582c96.png)

**Comment by ctschroeder** [comment]
again leaving open bc of all the metadata ingest issues

**Comment by ctschroeder** [comment]
also related to https://github.com/CopticScriptorium/cts/issues/14.  I understand they need to be configured manually, but one should not have to configure them manually each time one ingests.

**Comment by ctschroeder** [comment]
needs to be tested after ingest
