### ISSUE TITLE
Default behavior of URNs is List of HTML Formats

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#20]

**Comment by ctschroeder** [comment]
ok I think

**Comment by lukehollis** [comment]
When you visit a URN like http://coptic.aweb.io/urn:cts:copticLit:shenoute.A22:ya421-428, no HTML visualization is shown by default.

**Comment by ctschroeder** [comment]
That's a path, not a urn.  And it doesn't resolve to a list of HTML formats -- it's only showing the splash page.

**Comment by lukehollis** [comment]
The URN component of that path is outdated:  here's the updated version:  urn:cts:copticLit:shenoute.a22.monbya_421_428
