### ISSUE TITLE
Remove Titlecase from ingested SeachFields and SearchFieldValues from ANNIS

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#21]

**Comment by lukehollis** [comment]
Instead of automatically converting the display name for the search field metadata from ANNIS to titlecase, the ingest leaves all values as they were in the ANNIS metadata:  
![titlecase](https://cloud.githubusercontent.com/assets/2633382/6762650/bac1189e-cf3a-11e4-90bf-037b455f2e5c.png)

**Comment by ctschroeder** [comment]
Yeah, we need to clean up the metadata. Created issues in relevant corpora.

**Comment by ctschroeder** [comment]
This is related to the issue we noticed with the lists of annotators duplicating entries, so I'm not closing it until that gets sorted out.

**Comment by lukehollis** [comment]
Update here for the issue with the lists of annotators duplicating entries:  https://github.com/CopticScriptorium/cts/issues/22

This was related to differing numbers of spaces between the middle initial and last name.
