### ISSUE TITLE
Add "splittable" flag to Search Fields from ANNIS

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#22]

**Comment by lukehollis** [comment]
Hey @amir-zeldes and @ctschroeder, just need to know what this will look like in the XML retrieved from ANNIS to be able to implement a fix here.

**Comment by amir-zeldes** [comment]
Hi,

 

The idea for future proof extensibility is that the ‘splittable’ column in the table where metadata are stored together with priority etc. has a value that is either null, or a separator string, which we can set as we wish for each field. A sensible way to do it is to use comma-space (', ') as the separator for relevant fields, so that we can write: annotator="Carrie, Amir" and then the facetted search generates categories “Carrie” and “Amir”.

 

The ANNIS form for this is nothing special: it is simply a metadatum (in this case ‘annotator’) with a string value “Carrie, Amir”. It looks just like any other metadatum in the REST API.

 

Hope that’s clear, let me know if there are still questions.

 

Amir

**Comment by lukehollis** [comment]
Okay, this sounds good--so when I ingest the XML from ANNIS, it won't contain a "splittable" element that defines how to split the value.  This will just live on the side of the URN resolver, correct?

**Comment by amir-zeldes** [comment]
Yes, exactly. This way we can decide how we want the interface to behave without changing the underlying corpora, and not all formats would have a place to express this anyway.

**Comment by lukehollis** [comment]
Added this field to the data model in the resolver and customized the splittable search field values manually.  Will push the changes after the most recent ingest completes.

**Comment by lukehollis** [comment]
You can review this by the annotation search fields being split apart into single authors instead of each being a list of several authors: 
![annotation](https://cloud.githubusercontent.com/assets/2633382/6762613/3b153b7a-cf3a-11e4-9fb5-647d33236f29.png)

This also is the same on Translators

**Comment by lukehollis** [comment]
Reopened via https://github.com/CopticScriptorium/cts/issues/54 because the URN resolver administrative configurations necessary for the splittable field are no longer a viable option.  Could we develop a list of presets for terms we know we'll need to split from ANNIS?

**Comment by ctschroeder** [comment]
See my comments in https://github.com/CopticScriptorium/cts/issues/54

**Comment by amir-zeldes** [comment]
I don't think presets are necessary, I think we can just make the admin
settings for metadata names apply across documents. If annotator is a
splittable field for ap23 then it's splittable for ap25 too. No need to
make this configurable per document. Does that solve the problem?

sent from my mobile

**Comment by lukehollis** [comment]
Okay, that sounds good--I'll take another look at this and see if this will solve things.  The trick is that it has to rebuild all the search field values:

So the three search field values ingested from ANNIS:
Elizabeth Platte, Caroline T. Schroeder, Amir Zeldes
Rebecca Krawiec, Christine Luckritz Marquis, Caroline T. Schroeder, Amir Zeldes
Rebecca Krawiec, Christine Luckritz Marquis, Amir Zeldes

Need to be deleted and new search field values created associated to the same texts for:
Elizabeth Platte
Caroline T. Schroeder
Amir Zeldes
.. etc.

The Search Field Value to Text is a Many to Many relationship, and I'm not using a text search here.  

I'll look into making the settings for the metadata names apply across documents and see what I can come up with!

**Comment by lukehollis** [comment]
The splittable field now updates all associated SearchFieldValues each time a SearchField object is saved.  

The splitting process consolidates similar values and creates new SearchFieldValues objects and then removes the original SearchFieldValues.  

The SearchFieldValues for the annotation example in the previous comment now look like this:
![annotation](https://cloud.githubusercontent.com/assets/2633382/6989976/d70bc7f0-da30-11e4-8e18-30dea5420f4a.png)

I will roll out the other search tool changes mentioned in https://github.com/CopticScriptorium/cts/issues/54 after the next ingest completes.

**Comment by ctschroeder** [comment]
yes, also seems related, though, to the question of why there are duplicate entries.  Will leave this open until that is sorted out.

**Comment by lukehollis** [comment]
Okay, there was a small bug with the splittable field related to the most recent ingest modifications, but I fixed this issue with this most recent updates to our staging site this morning.  So, when we search for Amir in Annotations, I'm seeing correct results:  http://coptic.aweb.io/filter/annotation=7629:Amir%20Zeldes   

The duplicate entries for "Caroline T. Schroeder" are due to various spellings and spacing between the characters.  The "Caroline T. Schroeder" and "Caroline T.  Schroeder" which look very similar differ because there are two spaces between the "T." and the "Schoeder" in one of them, but only one space between them in the other. 

Here's the values for Caroline Schroeder that I have in the database for the "Annotation" SearchField: 
| 7628 | Caroline T. Schroeder  | Caroline T. Schroeder  |              96 |
| 7637 | Caroline T.  Schroeder | Caroline T.  Schroeder |              96 |
| 7638 | CarolineT.  Schroeder  | CarolineT.  Schroeder  |              96 |
| 7639 | CarolineT. Schroeder   | CarolineT. Schroeder   |              96 |
| 7640 | Caroline Schroeder     | Caroline Schroeder     |              96 |

**Comment by ctschroeder** [comment]
7628 and 7637 look identical to me.  As do 7638 and 7639.  ?  from what it looks like, there should be three entries not five.

**Comment by lukehollis** [comment]
Looks like the markdown condensed the spaces.  How's this?
```
| 7628 | Caroline T. Schroeder  | Caroline T. Schroeder  |              96 |
| 7637 | Caroline T.  Schroeder | Caroline T.  Schroeder |              96 |
| 7638 | CarolineT.  Schroeder  | CarolineT.  Schroeder  |              96 |
| 7639 | CarolineT. Schroeder   | CarolineT. Schroeder   |              96 |
| 7640 | Caroline Schroeder     | Caroline Schroeder     |              96 |
```

**Comment by ctschroeder** [comment]
Got it.  I have assigned my student to fix them.

**Comment by ctschroeder** [comment]
@amir-zeldes:  I fixed the known inconsistent metadata for annotators in the besa.letters repo and the ap repo.  They are ready for republication and ingest whenever you are.  Working on mark -- the whole bible repository is taking forever to sync.

**Comment by ctschroeder** [comment]
ok mark is ready https://github.com/CopticScriptorium/bible-dev/blob/master/Mark/mark.datafiles.may2015release.zip

**Comment by amir-zeldes** [comment]
Hi Carrie,

 

Thanks for updating the files – for now I’d like to avoid a complete release cycle. I just won’t have time before my visit and we don’t want to waste our time in CA on this. I’ve manually fixed the Caroline T. Schroeder variants via SQL in ANNIS, so that the ingest will work correctly. Your changes to the Excel will propagate to the PAULA and relANNIS versions in the next release cycle (I think these typos can wait till then). Is there anything else except Caroline T. Schroeder variants, before we run the ingest again? (have to get into regalia here in a sec…)

 

Amir

**Comment by ctschroeder** [comment]
That makes total sense. I really didn't care when it got published; just letting you know it was all fixed.  There is an inconsistency with Becky in Mark 12-15: remove the initial.

**Comment by amir-zeldes** [comment]
OK, Becky is done too, as is Sahidica metadata cleanup (no AP stuff). Should be ready for re-ingest.

**Comment by ctschroeder** [comment]
I am checking in from mobile devices for most of the day.  Do you all want to see how this works on the main ingest or the remote ingest? (I confess I am not clear on what the difference is at this point.)

**Comment by ctschroeder** [comment]
Also wld it be possible for one of you to ingest a couple of fussy corpora-- like a22, so, sahidica--just to see if the issues with the splittable fields are really fixed? We had both metadata errors and ingest bugs that we should test one more time. I can test from my iPad.

**Comment by lukehollis** [comment]
I can run a new ingest, configure the splittable fields and search tools order, and update the database for data.copticscriptorium.org.  Will update here when it's finished.

**Comment by amir-zeldes** [comment]
I ran an ingest for this site:

 

http://ec2-52-6-7-16.compute-1.amazonaws.com/

 

Then I remembered I had to change another item and re-ingested. Sadly all of the configurations (field order, splittability) were erased in the process. Is there some way to prevent them from being overwritten?

 

I’ve restored that information and now that site is now up to date with the latest ANNIS content.

**Comment by lukehollis** [comment]
We discussed having presets for the "order" and "splittable" fields but on March 21 on this ticket, @amir-zeldes, you mentioned that you didn't want to use presets "order" and "splittable" fields.  We then discussed adding "order" and "splittable" fields to ANNIS metadata but decided not to add these to ANNIS as mentioned in this ticket on March 6th and March 17th: https://github.com/CopticScriptorium/cts/issues/14.  So the order and the splittable fields must be refreshed with each ingest.

**Comment by ctschroeder** [comment]
Thank you!  And yes, I echo Amir's request. I thought we talked in a Skype meeting a couple weeks ago about setting the configurations so they would not reset each time.  thanks!

**Comment by amir-zeldes** [comment]
Yes, I still think they shouldn’t be ANNIS metadata, since that puts things in metadata that only have to do with the way this repo is run (not something integral about the corpora). But I do think they should persist across ingests, at least unless the corpus they apply to has been deleted. I don’t foresee we’ll change our minds about ‘annotation’ being splittable (or its priority very often), so having to reset these manually every ingest seems like an unnecessary task.

**Comment by amir-zeldes** [comment]
Oh, and @ctschroeder, take a look at the amazon site with the latest ingest, I think the metadata looks correct now!

**Comment by ctschroeder** [comment]
The ingest looks good. Thanks!   I think that the resolution in issue 14 was not clear.  I know I took the comment that manual configuration in the resolver was possible to mean that there was a way to do this without configuring with each ingest.
