### ISSUE TITLE
Convert HTML Visualizations to content type associated with Corpus

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#25]
When the ingest will query ANNIS for a given corpus, it will retrieve a list of Docnames and query each docname with the HTML visualization type specified on the corpus

**Comment by lukehollis** [comment]
HTML Visualization ingested and displayed in tabs are now generated dynamically as specified with each corpus in the URN resolver cache.

**Comment by ctschroeder** [comment]
This is looking good, except there are no analytic viz showing up for the Abraham Our Father corpus.  They exist in ANNIS, however.  ?

**Comment by lukehollis** [comment]
The analytic view has been added for AOF with the most recent ingest.  

![aof](https://cloud.githubusercontent.com/assets/2633382/6991201/3e7988d2-da54-11e4-9c13-592fb668979c.png)

**Comment by ctschroeder** [comment]
this seems related to Amir's email about the ANNIS API yesterday. Can't close because I don't know if that has been integrated, yet.

**Comment by lukehollis** [comment]
Yes, the HTML visualization formats are a content type associated with each corpus.

Here's a screenshot from the A22 corpus object in the resolver showing the selected HTML visualization formats near the bottom:
![corpus2](https://cloud.githubusercontent.com/assets/2633382/7633529/8d8b1cc2-fa22-11e4-9595-2d4146b5b946.png)

**Comment by ctschroeder** [comment]
@amir-zeldes , when you tested the ingest, was this all working alright? Thanks!

**Comment by ctschroeder** [comment]
should check after next ingest @amir-zeldes

**Comment by amir-zeldes** [comment]
Was fine last time as far as I know, but we should check this again with latest ingest to see that Eagerness is behaving correctly when a new corpus is added. Leaving open till next ingest.
