### ISSUE TITLE
Reflect search parameters selected in the URL so that any state of the search is sharable/reproducable

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#26]

**Comment by lukehollis** [comment]
All search filters are now reflected after the /filters/ route handled by the client-side angular application.

**Comment by ctschroeder** [comment]
search? are we talking about full text search or the filtering through the menu? Tests I ran seem to work if the latter is the case.

**Comment by lukehollis** [comment]
Yes, this is meant for the search filters through the menu since we've removed the text search input field for the time being.

**Comment by ctschroeder** [comment]
ok
