### ISSUE TITLE
Make full text search work

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#28]

**Comment by lukehollis** [comment]
Added functionality to full text search.  Full text search bugs tracked in this ticket: https://github.com/CopticScriptorium/cts/issues/48

**Comment by ctschroeder** [comment]
There was another full-text search ticket. I replied there: hide it if linking to ANNIS is too complicated/beyond current contract.  It is definitely still slow.

**Comment by lukehollis** [comment]
Full text search is hidden for the time being.

**Comment by ctschroeder** [comment]
Can we close this?
