### ISSUE TITLE
Investigate slow response time on site

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#29]

**Comment by lukehollis** [comment]
I still haven't been able to reproduce this on various networks/devices in Cambridge.  This may be something that I have to take up with my hosting provider.  Any more updates on your end, @amir-zeldes ?  Will keep investigating this for now.

**Comment by lukehollis** [comment]
Optimized queries, esp initial for corpus.  Site responsiveness on coptic.aweb.io to me is still instantaneous, so let me know if things are still slow for you both.

**Comment by amir-zeldes** [comment]
Just tested it again and I’m seeing fast responses now for the first time. I can’t reproduce the slowness, though it was 100% consistent previously. If it now works well for Carrie as well then all is well, thanks.

**Comment by lukehollis** [comment]
Terrific!  That's good to hear.  I was thinking I was crazy for a bit there.  Glad that everything's working faster.
