### ISSUE TITLE
Add editor for ordering SearchFields and placing some in an overflow dropdown menu

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#3]

**Comment by lukehollis** [comment]
A site administrator can now order and rearrange search fields in the primary and advanced search fields in the search tools toolbar. 
![searchfield](https://cloud.githubusercontent.com/assets/2633382/6762808/9315fb68-cf3d-11e4-947a-fa72c65f86c1.png)

**Comment by ctschroeder** [comment]
ok sounds good.

**Comment by ctschroeder** [comment]
This has to stay open until we test it on a new ingest.  Last time we tried a new ingest, all the filter fields got switched around.  It's not really at a final review stage, yet.

**Comment by lukehollis** [comment]
Because we decided not to add the "order" field to ANNIS and we decided to ingest the search fields from ANNIS without presets to determine the order, every time the ingest runs, the order of the search fields will have to be reset.   

The "order" field on the search field determines the order of search fields that appear in the search tools.  Since we decided to hide the Advanced Search Fields, only the first five search fields ordered by the "order" field will appear in the search tools.  

Here's another screenshot of what the order field on the "corpus" searchfield (which appears first in the search tools) looks like:

![searchfield](https://cloud.githubusercontent.com/assets/2633382/7633424/de9bb7da-fa21-11e4-8ca8-64e0dd2f4d87.png)

**Comment by ctschroeder** [comment]
leaving this open bc there are so many metadata ingest issues right now

**Comment by ctschroeder** [comment]
this sounds related to issue 14 https://github.com/CopticScriptorium/cts/issues/14

**Comment by ctschroeder** [comment]
this is good.
