### ISSUE TITLE
Sometimes Angular HTML binding performing slowly (adding 1-5 second break between loading modal fading and HTML single modal appearing)

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#33]

**Comment by lukehollis** [comment]
Updated the hide_loading_modal trigger based on the HTML visualization being loaded on the client.

**Comment by ctschroeder** [comment]
Still seems slow, but I have no idea why and so no idea whether this ticket should close.

**Comment by lukehollis** [comment]
I migrated the database engine from sqlite to mysql, which increased site performance and responsiveness, so this issue should be resolved.  If there are still problems with performance in the future, we can introduce a simple object cache for the api.  Otherwise, this ticket is ready to close.
