### ISSUE TITLE
Correct A22 TEI repository links

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#34]

**Comment by lukehollis** [comment]
Fixed this field on the collection object--thanks for the insight here, @ctschroeder!

**Comment by ctschroeder** [comment]
Thanks.  Or this:
https://github.com/CopticScriptorium/corpora/tree/master/shenoute-a22/shenoute.a22_TEI

The diplomatic visualization seems to be broken.  Please compare what is showing on the urn site to the what is in ANNIS:
![screen shot 2015-03-20 at 8 16 04 am](https://cloud.githubusercontent.com/assets/4079217/6754378/63738e2a-ced9-11e4-8948-864d21e2a6d1.png)

**Comment by lukehollis** [comment]
Why some of features from the HTML visualizations aren't appearing in the cached content is still under review in this ticket: https://github.com/CopticScriptorium/cts/issues/24  Thanks for pointing out the troubles with the diplomatic HTML visualization.  The TEI repository link issue is resolved.
