### ISSUE TITLE
Add input field for entering URNs manually

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#35]

**Comment by lukehollis** [comment]
Still need some helps for error handling and 404s with incorrect URLs, but this should get us moving in the right direction.  Is this what you were envisioning, @ctschroeder?  Let me know what you think!  Hope all's well--

**Comment by ctschroeder** [comment]
Yes I see it.  Thanks.  This is what I mean.  It didn't work when I typed in a URN, but you're working on it right this second.
We don't have a 404 page.  We should.  If you want to make a plain one, feel free -- I can edit it to conform to our branding.  (Don't spend time on it, in other words -- a placeholder is fine.)

**Comment by amir-zeldes** [comment]
Looks good to me too, always a good idea in case we get a user who thinks “where do I put in this URN thingie?”

**Comment by lukehollis** [comment]
Good deal--glad to hear you both like this feature!  I've tested many URNs with it, and so far all of them have worked.  We do have a 404 page that conforms to site branding, but the site for the moment is in development mode, so the 404 prints a stack trace and other useful debugging information.

**Comment by ctschroeder** [comment]
Ok. 

carrie@carrieschroeder.com

**Comment by balmas** [comment]
Just a note: I've become completely addicted to the typeahead that Thibault implemented for our new CTS selector:  https://github.com/Capitains/jQuery.typeahead  -- it could possibly be reused here -- we could talk about this next week if you want!

**Comment by lukehollis** [comment]
I love it!  Sounds terrific.  If @ctschroeder and @amir-zeldes think that it would be a good idea and not outside of scope here, I'm all for it. Thanks!

**Comment by ctschroeder** [comment]
Thanks!  Generally, I trust @balmas judgment, if you think something is good/useful.   I would like to know more about pros/cons, especially sustainability. (One pro seems like ease of use as our corpora expand.) @balmas we can talk next week if you'd like.  @amir-zeldes will be traveling.  I think Luke should move on everything else for the time being; we won't be able to decide until after I've learned more anyway.

**Comment by lukehollis** [comment]
Given our deadline this week, any final thoughts on this issue?  It seems like it'd be great to add in the next iteration of this project.

**Comment by balmas** [comment]
Sorry, we never did really get to talk about this did we? I'm thinking that since you don't have an actual CTS endpoint, I'm not sure if the Capitains typeahead code will work out of the box for you, but I still agree the ability to have typeahead support would be very nice to have here. One bit of feedback from our own implementation though -- we somewhat naively assumed that if we gave people typeahead support on author/work that automatically resolved to the cts urn, they wouldn't need to have the ability to browse (or e.g. select from dropdowns) form available values for these - both are really needed though.

**Comment by ctschroeder** [comment]
I'm not going to be able to think about this for a while.  Have a million deadlines this month.

**Comment by ctschroeder** [comment]
closing this since I think we are all in agreement that the Capitains code is not something we can do right now.
