### ISSUE TITLE
Dropdowns covering page content

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#39]
This is how many dropdowns work, but we certainly can change this if need be.  Let me know your thoughts!  Moving the page content up and down based on the height of the dropdown may be a little disorienting for some users.

**Comment by lukehollis** [comment]
Maybe another question is if we should have "hover" or "click" interactions on the dropdowns.  Either are good options!

**Comment by lukehollis** [comment]
Added x's to close the dropdowns.  Can retools this anyway we need to, but hopefully this will solve the main part of the problems we were experiencing with the dropdown menu. 
![dropdownx](https://cloud.githubusercontent.com/assets/2633382/6734720/26212b62-ce30-11e4-8c6d-3a04df3a4ccc.png)

**Comment by ctschroeder** [comment]
The box is good.  The branding ended up going a bit too far though, and the format is all changed

Go back the old format, then:
add our floating nav bar to the top
put the URN box back on the right where it was before. that had a very clean look
you can keep our banner on the top with the manuscript image in the background or you can just use the white background logo but please get rid of the manuscript image for the rest of the page.  If you want to make it look like our other pages, that image is brightened substantially -- see our css https://github.com/CopticScriptorium/CopticScriptorium.github.io/blob/master/scriptorium.css with 	background-color: hsla(40,53%,100%,0.80);  The ms image has an 80% brightness on our homepage for the content box.  Given the format you have here with the rows I recommend eliminating it or fading it out dramatically in the background of the content area.
For now keep the font and the brown background for the menu-- that looks good

**Comment by ctschroeder** [comment]
Maybe start by eliminating it at least for content.

**Comment by ctschroeder** [comment]
This looks good.  Thanks! I think ready to close.
