### ISSUE TITLE
Add URN meta spec and namespace to the HTML

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#42]

**Comment by lukehollis** [comment]
![meta](https://cloud.githubusercontent.com/assets/2633382/6702890/17e0362e-cd09-11e4-8f72-aadf5bcba891.png)

Meta tags added for documents and corpora.

**Comment by lukehollis** [comment]
Waiting here for ingesting the MSS sigla msNames from ANNIS for each document, via https://github.com/CopticScriptorium/cts/issues/43.

**Comment by lukehollis** [comment]
Updated the msName URN from ANNIS here:  
![meta_html](https://cloud.githubusercontent.com/assets/2633382/6761898/47b71bde-cf2e-11e4-81b0-3ad572b06b57.png)

**Comment by ctschroeder** [comment]
Ok, msName looks good.  The doc names are still off I think.  I need to go through them all on that table we keep talking about happening :)

**Comment by ctschroeder** [comment]
think this is ok to close...
