### ISSUE TITLE
Use the rest API from ANNIs to find all the msNames

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#43]
Hey @amir-zeldes, I've been trying to reverse engineer the ANNIS api to get this information, but I'm not sure where I can find the list of msNames and how I can marry data that with the docName or corpus meta query.  We could also set this information manually for each corpus object defined in the resolver.  Thanks again for all your help with the queries to ANNIS!  I think we're almost there!

**Comment by lukehollis** [comment]
Implemented and waiting for new ingest after fixing a few errors.

**Comment by lukehollis** [comment]
All msNames ingested from document specific metadata and appearing in the ANNIS Metadata section on each text/document.

**Comment by ctschroeder** [comment]
looks like it's working to me
