### ISSUE TITLE
Complete documentation / docstrings  for application

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#44]

**Comment by ctschroeder** [comment]
I don't know how review and comment on this.  Need more information, link to the documentation, etc.

**Comment by lukehollis** [comment]
The docstrings/documentation here are referencing the documentation in code.  Things always change a little bit in development/testing/review, so this was mostly a ticket to myself to make sure that all the documentation for the code was up to date with the code by the first commit on the github repo.  Here's one file where you can see the documentation strings (in triple quotes or behind a #) in action: https://github.com/CopticScriptorium/cts/blob/master/coptic/texts/models.py

**Comment by ctschroeder** [comment]
I can almost follow this and don't know Python, so this is probably ready to close. Don't know if @amir-zeldes wants to take a look next week, first.
