### ISSUE TITLE
HTML visualization templating breaking on <ruby>, <rt> elements

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#45]
Occasional trouble adding unsanitized HTML from visualizations containing 
```
<ruby>
``` 
and 
```
<rt>
``` 
elements

**Comment by lukehollis** [comment]
Angular sanitize trusts the HTML as safe.

**Comment by ctschroeder** [comment]
I'm not going to be able to comment on this without links to examples.

**Comment by lukehollis** [comment]
Here's a link to an HTML visualization with <ruby> and <rt> elems: http://coptic.aweb.io/texts/ap114theophilus/analytic  

The angular templating here wasn't rendering the HTML for the visualization ingested from ANNIS at all before fixing this bug.

**Comment by ctschroeder** [comment]
Thanks for clarifying.  The Analytic vis still not working at all.  
Compare to ANNIS:

On 3/20/15 3:03 PM, Luke Hollis wrote:
>
> Here's a link to an HTML visualization with and elems: 
> http://coptic.aweb.io/texts/ap114theophilus/analytic
>
> The angular templating here wasn't rendering the HTML for the 
> visualization ingested from ANNIS at all before fixing this bug.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CopticScriptorium/cts/issues/45#issuecomment-84166077>.
>


-- 
________________________________
C. Schroeder
Associate Professor, Religious and Classical Studies
The University of the Pacific

carrie@carrieschroeder.com
http://www.carrieschroeder.com
https://pacific.academia.edu/CarolineSchroeder

Coptic SCRIPTORIUM
http://www.copticscriptorium.org

Blog
http://www.earlymonasticism.org

**Comment by lukehollis** [comment]
Okay, I'll take another look at this and update the pseudoelements ticket for the HTML not displaying properly: https://github.com/CopticScriptorium/cts/issues/24

**Comment by ctschroeder** [comment]
Ok, thank you. Please keep this really simple.  We need to be able to do this for future documents or revised documents without having to update the styles in your database.  If it requires a lot of manipulation, we need to discuss.  The idea is to be able to bring the HTML visualization in easily from the ANNIS API.  Our goal is to build the data and css once, which we access in multiple ways.  If it is too difficult to visualize the html on the page with the information, etc, then we need to rethink the design of the site.  We are a small shop and can't spend hours fussing with the css, etc., on ANNIS and then again here.  Must be transferrable, reusable, etc.
We also had discussed caching the viz when it's created the first time, and until a new update, subsequent users would view the cached html -- not recreate the html each time.
Thanks.

**Comment by lukehollis** [comment]
Yep, it looks like it might be more simple to just load the ANNIS HTML visualization with an iframe instead vis this ticket: https://github.com/CopticScriptorium/cts/issues/23.  Nothing should require a lot of manipulation.

**Comment by ctschroeder** [comment]
yes, whatever. we can even send people to a new window if necessary. anything to keep it simple.

**Comment by lukehollis** [comment]
P.S. I'm a small shop too--I understand!
