### ISSUE TITLE
Display document-specific metadata from ANNIS on text document single view

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#47]

**Comment by lukehollis** [comment]
Updating the title here now that we've ingested the document-specific metadata from ANNIS

**Comment by lukehollis** [comment]
The document-specific metadata from ANNIS appears on the single selected text view:  
![annis_metadata](https://cloud.githubusercontent.com/assets/2633382/6761085/c52d9cea-cf25-11e4-88f0-ea06aed07989.png)

**Comment by ctschroeder** [comment]
Yes, looks right.
