### ISSUE TITLE
Bugs with Text Search (slow, false positives)

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#48]

**Comment by lukehollis** [comment]
It seems like it might be better to not include a full text search at the moment or potentially that it would be out of scope for a URN resolver with simple search tools.  Let me know your thoughts here.  Would be great to turn the search box into a linked ANNIS query!

**Comment by amir-zeldes** [comment]
If you want to look at ANNIS queries, you can just run one and copy-paste the URL out of the interface. Basically the query is base64-ed in another URL parameter, just like the corpus selection etc.

**Comment by ctschroeder** [comment]
The decision is to hide it or link to ANNIS.  If the link to ANNIS is too complicated, you may hide it for now. We should probably reticket this, not close it.

**Comment by lukehollis** [comment]
Hidden for now--let me know when you want to prioritize linking the query to ANNIS.

**Comment by ctschroeder** [comment]
Ok, I think we can close for now.
