### ISSUE TITLE
need to license Luke's code

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#49]
@amir-zeldes & @lukehollis : what license do you want to use for Luke's code?  We should put it somewhere on the site.  Since it is code, we should probably use gnu or apache? We need to credit Luke but also probably Bridget

**Comment by amir-zeldes** [comment]
I like Apache 2.0 since it’s non-copy left. ANNIS, SNP etc. are all Apache 2.0.

**Comment by lukehollis** [comment]
Apache 2.0 license included here: https://github.com/CopticScriptorium/cts/blob/master/LICENSE

**Comment by ctschroeder** [comment]
Ok. We just need to reference it properly somewhere, probably in the footer and then on our main "about" page.  Typically you link to the apache site, as with Creative Commons, correct? If you, @lukehollis, and @balmas are good with this license.  It is your work, also.

**Comment by ctschroeder** [comment]
The license language looks fine, but for some reason the hover color on the links is not working properly.

**Comment by lukehollis** [comment]
Okay, I'm showing the hover color on all footer links working properly.
