### ISSUE TITLE
Refactor document specific URN resolver

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#5]

**Comment by lukehollis** [comment]
Based this on docname value ingested from ANNIS.

**Comment by lukehollis** [comment]
The document URN code is now based on the docname ingested from ANNIS instead of the native URN resolver slug.  These can be edited in the future by editing the titles of ingested Texts by a site administrator.

**Comment by ctschroeder** [comment]
I don't understand the implications of the change.  I understand only "The document URN code is now based on the docname ingested from ANNIS "

**Comment by lukehollis** [comment]
This ticket was mostly for myself just to say that I got the docname from ANNIS and used it in the URN.  This part of the URN can be easily edited by an administrator anytime in the future.

**Comment by ctschroeder** [comment]
Ok, yeah, we need to go through those.  (Sorry to be a broken record, but it's helpful to me to put it everywhere it's relevant so I know I saw this issue and also know the next step.)
