### ISSUE TITLE
table of urns

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#50]
Can you please send me a link to the table of the canonical urns?  I want to make one last review.  The Abraham one looks strange to me.  
If I make changes to them, how difficult will that be for you to implement? I want to be sure we get it right.

**Comment by ctschroeder** [comment]
@lukehollis I still need the link to this table.  Some of the URNs I'm seeing are not right, and even though we discussed checking in on the AP urns before implementing the URN resolver, that didn't happen.  There are a number I need to edit.  Thanks.

**Comment by lukehollis** [comment]
Hey Carrie, I'm using the inventory developed by Bridget (https://github.com/CopticScriptorium/cts/tree/master/inventory) and still need to put together a table of all the URNs based on the data ingested from ANNIS.  These are available through the JSON API manifest (http://coptic.aweb.io/api/manifest/), so I need to make a view for them in the resolver.  Any administrator can edit and configure the URN settings at any time in the future.

**Comment by ctschroeder** [comment]
Ok, but some of those were supposed to be changed, like the AP. So Bridget's list is not up to date. I can look at the list through the API but will need access to wherever they live so that I can finalize them. The idea is to mint URNs that are stable and permanent. Thanks so much!

carrie@carrieschroeder.com
Sent from my iPhone

**Comment by lukehollis** [comment]
Yes, that sounds good!  I'll send you a link to the view for the table of all possible URNs as soon as I have created it.

**Comment by ctschroeder** [comment]
Hi. When you say "create" do you mean create a UI? I don't need a UI; just point me to the code or file. Thanks!

carrie@carrieschroeder.com
Sent from my iPhone

**Comment by ctschroeder** [comment]
I'm not sure where to put this, but here seems as good a place as any.  This is for my reference for checking the URN list and also for checking the visualization of everything on the relevant webpage. This info is from @balmas :

"The format paths were meant to be paths to specific representations of the text represented by the URNs.  So I think the formats should only be used in the context of the full URLs to these representations:

i.e.

http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/dipl/html

I think however for citing the text and corpus in general, use of the URN alone is probably sufficient and correct, because there you're not citing a specific representation. 

And since the live version Annis is a different representation than the archived relAnnis files (even if the same data) then it would have its own path

So that would mean this for the how to cite this text section:

Text (General): urn:cts:copticLit:shenoute.A22:ya421-428

dipl HTML: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/dipl/html

norm HTML: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/norm/html

TEI XML: http://copticscriptorium.org/ urn:cts:copticLit:shenoute.A22:ya421-428/tei/xml

Paula XML: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/paula/xml

reIANNIS: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/reiannis

ANNIS UI: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/annis

Corpus: urn:cts:copticLit:shenoute.A22 

However, this is a pretty big list. It might make it simpler for the end user if you didn't list all options on all formats, or if you put them in a preferred order.  I.e. maybe on the dipl display you would have:

In order to cite this document, please use the following URN structure:

This representation (dipl HTML): http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/dipl/html

Text (General): urn:cts:copticLit:shenoute.A22:ya421-428

Corpus: urn:cts:copticLit:shenoute.A22
Other representations:

norm HTML: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/norm/html

TEI XML: http://copticscriptorium.org/ urn:cts:copticLit:shenoute.A22:ya421-428/tei/xml

Paula XML: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/paula/xml

reIANNIS: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/reiannis

ANNIS UI: http://copticscriptorium.org/urn:cts:copticLit:shenoute.A22:ya421-428/annis

**Comment by ctschroeder** [comment]
Summary of 4/2 conversation:
I think we know what the base URNs are out to the edition level for everything but the AP corpus:

urn:cts:copticLit:shenoute
urn:cts:copticLit:shenoute.a22
urn:cts:copticLit:shenoute.a22:MONB-YA
urn:cts:copticLit:shenoute.a22:MONB-YB
(etc. as we add more codices/editions -- this is true for all the corpora)
urn:cts:copticLit:shenoute.aof
urn:cts:copticLit:shenoute.aof:MONB-XL
urn:cts:copticLit:shenoute.aof:MONB-YA
urn:cts:copticLit:shenoute.aof:MONB-ZH
urn:cts:copticLit:shenoute.fox
urn:cts:copticLit:shenoute.fox:MONB-XH

urn:cts:copticLit:besa
urn:cts:copticLit:besa.aph
urn:cts:copticLit:besa.aph:MONB-BB
urn:cts:copticLit:besa.thieving
urn:cts:copticLit:besa.thieving:MONB-BA
[NOTE:  I changed it from nuns to thieving, because I take issue with Layton's translation of monache as "nun" in a forthcoming review of his book, and just generally don't like this term for monache.]

urn:cts:copticLit:nt
urn:cts:copticLit:nt.mark
urn:cts:copticLit:nt.mark:sahidica
urn:cts:copticLit:nt.mark:sahidica-ed
urn:cts:copticLit:nt.mark:sahidica:01
urn:cts:copticLit:nt.mark:sahidica-ed:01

The only strange thing is that this will mean you can't easily find all the data and their representations for chapter 1 of Mark as a conceptual thing.  (Because we have two editions of Sahidica, and the hierarchy is by edition not conceptual work.)

The "how to cite this document" instructions will give people the above URNs plus some of the URL paths to the data; it will not have page numbers of the codices (corresponding to documents YA421-28, etc.) on the URNs themselves.  We will advise people to put the ms page or page range in their citation and the date they accessed the data.  E.g., write something like:
To cite a specific page or section of this document, append the page numbers to the end of the URN.  Examples:
urn:cts:copticLit:shenoute.a22:MONB-YA:423
urn:cts:copticLit:shenoute.a22:MONB-YA:424-425

If someone has urn:cts:copticLit:shenoute.a22:MONB-YA:424-425 and enters it in the URN box -- it will resolve to the correct documents/data and representations.  Because at ingest, the metadata for the edition (manuscript or sahidica edition) and start/end fields will be used to determine what resolves where at the edition (eg., MONB-** or sahidica) and "passage" level.   So urn:cts:copticLit:shenoute.a22:MONB-YA:424-425 will resolve to a list of all the representations of the latest data for our document YA421-28.  

NB: nb: we need to add consistent fields for edition, start, end in each document's metadata.  This may mean we duplicate data.  (e.g., MONB.YA will appear in a manuscriptName field and an edition field).  But having one named field across corpora will be helpful.  (Amir: I've hired a student who can help with this.  He knows nothing about websites or programming but can handle banging out stuff in an Excel file.)

Additional note we did not discuss:  There are going to be occasions where a page or part of a page no longer has a page number, but the scribe's hand or content tells us which codex they belong to; these are typically called fragments:  fragment 1a/b, fragment 2a/b, fragment 3a/b, fragment 4a/b (where a and b are each side of the page, and the fragment is the leaf).  I think in the metadata we should call those 0.01.1, 0.01.2, 0.02.1, 0.02.2 etc. so they are countable and semantically meaningful enough.  (Currently there are not more than 99 unplaced fragments identified with each codex, but we just saw that presentation at our conference about all the White Monastery fragments Yale just discovered and digitized, so who knows....)

Additional note #2:  The Besa corpus does have canonical sections (not ms page numbers but paragraph #s I.1, I.2, I.3, II.1, II.2, II.3) that are not tied to the manuscript. And these are encoded on our corpus on the data level, not metadata.  While it would be possible to include start/end metadata for these sections, we have not figured out what a URN for that would look like.  We might need to save this for another phase unless Bridget has an easy answer for this situation.

We still have not figured out how to deal with the AP corpus which is a hierarchical nightmare.  I will ponder.

**Comment by lukehollis** [comment]
In response to this, I accessed the pages_from, pages_to, and chapter metadata fields ingested from ANNIS and used them to generate and resolve passage level URNs.  I also added the Textgroup URN to the citation panel but can remove this if it should not be there.  I'm still testing this to work out remaining bugs but hope it can add a tangible step in the right direction from our discussion.

Ex:
![a22](https://cloud.githubusercontent.com/assets/2633382/6992861/bfce9616-daae-11e4-9e02-2a251e39fafe.png)

**Comment by ctschroeder** [comment]
Thanks for working on this!

The urns are still not quite right.  See my email from Thursday summarizing.  I'm quoting here from it:

urn:cts:copticLit:shenoute (author text group)
urn:cts:copticLit:shenoute.a22 (text/corpus)
urn:cts:copticLit:shenoute.a22:MONB-YA (edition/manuscript)
urn:cts:copticLit:shenoute.a22:MONB-YB
(etc. as we add more codices/editions -- this is true for all the corpora, though AP is unusual)

urn:cts:copticLit:shenoute.a22:MONB-YA:421-428 is the document represented at the passage (page) level, not the text.  Please make note of the periods and colons and dashes.


All of the HTML, TEI, Paula, ANNIS references can be represented as URLs with paths. They are not cts urns in and of themselves. See Bridget's and my emails from last week, which give examples. E.g. http://www.copticscriptorium.org/urn:cts:copticLit:shenoute.a22:MONB-YA:421-428/norm/html

I give a lot of the urns in my email from Thursday night.

Thank you!

**Comment by lukehollis** [comment]
This all looks great!  I have one question about the edition/manuscript URN codes:   the msNames from ANNIS have a period between MONB and YA whereas the URNs have a dash.  Since the edition/manuscript is ingested automatically from ANNIS for each text, can I always convert the period to a dash?   (So from ANNIS, the msName ingested will be MONB.YA or MONB.YB, but in the URN, it will  be MONB-YA or MONB-YB?)

**Comment by ctschroeder** [comment]
The period in MONB.YA etc outside of the urn system is just a convenient divider between MONB (which stands for "white monastery" in Italian) and the two letter codex siglum that follows. We need to change it to something else in the urn bc as bBridget said, in urns, the period has a specific function and meaning. Given that, I think it should always be changed to dash. 

However, the corpora that don't have msName (the New Testament corpora) are going to have a different field in ANNIS that corresponds to the edition space in the urn, as we discussed Thursday. Please see the email from Thursday to see how these all should resolve. 

As I said in my email, Bridget recommended we add consistent metadata field names to each document to enable this automatic ingest. I am not going to be able to do that by Tuesday. Amir and I need to decide on the field names and then we need to add them to every file, ingest into ANNIS, etc. that is a long process. 

For now you will have to tell the system at ingest which field to look in for which corpora, and how to resolve to the edition part of the urn. Does that make sense?  We talked about it Thursday. 

Thanks.

Carrie

carrie@carrieschroeder.com

**Comment by lukehollis** [comment]
Yes, that all makes sense, and I remember our conversation about the corpora that don't have an msName metadatum set.  For the moment I've made the change from period to dash for the msNames that are set.  Thanks!

**Comment by ctschroeder** [comment]
Following Bridget's work on the inventory, the URNs for the AP should reflect that the text GROUP is the ap. Each individual saying is the text.  We probably need to change the title field in the inventory below; the title is for saying 1.  
So group name is The Apophthegmata Patrum.  
Title is something like The Apophthegmata Patrum Coptic 001.  The 001 in the work urn refers to the saying number.  
The languages should be changed to cop from grc.
   <textgroup urn="urn:cts:copticLit:ap">
        <groupname xml:lang="eng">The Apophthegmata Patrum</groupname>
        <work urn="urn:cts:copticLit:ap.001" xml:lang="grc">
            <title xml:lang="eng">The Apophthegmata Patrum</title>
            <edition urn="urn:cts:copticLit:ap.001.MONB_EG">
                <label xml:lang="eng">White Monastery Manuscript EG</label>
            </edition>
        </work>
    </textgroup>
Each AP text/document has a number in it.  That number should be the number in the URN for that work.  We are in the process of changing the file names for each work within our AP corpus, but regardless, that number will be in the file name and should be in the URN.  It should be a 3-digit code (even if the file name in ANNIS or on GitHub or wherever has only one or two digits).

textgroup urn="urn:cts:copticLit:ap"
work urns are: 
urn:cts:copticLit:ap.001 (we don't have this one in our corpus, yet; our current earliest is #22 I think)
urn:cts:copticLit:ap.022
urn:cts:copticLit:ap.023
urn:cts:copticLit:ap.114
etc.

edition urns are 
urn:cts:copticLit:ap.001.MONB-EG
urn:cts:copticLit:ap.022.MONB-EG
urn:cts:copticLit:ap.023.MONB-EG
urn:cts:copticLit:ap.114.MONB-EG
etc.

**Comment by ctschroeder** [comment]
In other words:  @lukehollis , please use this system for the AP urns.  Also someone needs to update the XML manifest, etc., of Bridget's original work.

**Comment by ctschroeder** [comment]
the inventory is now complete
