### ISSUE TITLE
mySQL schema

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#51]
@lukehollis can you share the database schema with us before we sign off on all this?  @amir-zeldes may want to look at it, and I think I want my spouse to give it a once-over.  Thank you!

**Comment by lukehollis** [comment]
Sounds great!  The best way to review this right now is looking at the models, available here:

annis: https://github.com/CopticScriptorium/cts/blob/master/coptic/annis/models.py
ingest: https://github.com/CopticScriptorium/cts/blob/master/coptic/ingest/models.py
texts: https://github.com/CopticScriptorium/cts/blob/master/coptic/texts/models.py

Let me know if you'd prefer a different format, and I'll send it your way.
