### ISSUE TITLE
Cite this document panel

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#52]
@ctschroeder will want to add more static/universal content to the "Cite this document" panel.  Prose content.  Exact content ctschroeder will add will depend on whether the document level metadata is exposed or hidden (see https://github.com/CopticScriptorium/cts/issues/18).

**Comment by ctschroeder** [comment]
So @lukehollis at the end of the process will need to point me where to go.  This is NOT urgent; for the very end.

**Comment by lukehollis** [comment]
Okay, that sounds great!  The URNs/Cite this data starts here: https://github.com/CopticScriptorium/cts/blob/master/coptic/templates/index.html#L86  Let me know what else I can help with here.

**Comment by ctschroeder** [comment]
Also panel needs to say that the urns resolve to the latest edition of the data.  Citations by scholars should include date accessed in their fns; if you're looking for earlier data, then go to GitHub for archives

**Comment by lukehollis** [comment]
The Cite this Document panel has been updated to reflect the text from your ticket here.  If you'd like something verbatim, send it my way, and I'll apply it to the view.  Otherwise, as the earlier ticket mentions, the text is here: https://github.com/CopticScriptorium/cts/blob/master/coptic/templates/index.html#L86

**Comment by ctschroeder** [comment]
leaving open for now; @ctschroeder needs to make revisions to this section

**Comment by ctschroeder** [comment]
leaving open for now; @ctschroeder needs to make revisions to this section

**Comment by ctschroeder** [comment]
done.
