### ISSUE TITLE
Changing display names for HTML formats (from dipl to Diplomatic, norm to Normalized, etc)

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#53]
If you navigate to this page in the administrative view, http://coptic.aweb.io/admin/texts/htmlvisualizationformat/, you will see the four specified HTML formats that currently exist on the site. To change the display name for one (not the internal ANNIS name, but the one that appears for users on the URN resolver app), click on the title of the format you want to change.  Then edit the title to the value you want to be shown on the site.  
![norm](https://cloud.githubusercontent.com/assets/2633382/6763084/99962f1a-cf44-11e4-8b2c-287b38c62eee.png)
![norm2](https://cloud.githubusercontent.com/assets/2633382/6763086/9ab6d17e-cf44-11e4-805b-4827d02174e7.png)

These values can be changed anytime in the future, so let me know what your thoughts are here.

**Comment by ctschroeder** [comment]
title and button title edited; slug left the same since that is what is linked to ANNIS
