### ISSUE TITLE
Remove list of documents and visualizations from index page

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#56]
From our emails: "1. Splash page should be redesigned to be static page stating what the endeavor is, rather than something that generates all possible data and visualizations"

**Comment by lukehollis** [comment]
Also Amir's response from our emails: "Yes, splash page should not load all documents, but search panel should still be there. We should try to avoid loading ‘everything’ when the user clears search criteria. If they want to “show all” we could either make a button for that or they could search for project=scriptorium or something like that, but clearing all search criteria should not show all documents (especially thinking about NT). I think this may help with 2. as well."

**Comment by lukehollis** [comment]
The default view for the resolver now is filler copy that I can replace if you send a project description my way.  Otherwise, you can edit the HTML templates directly yourselves here: https://github.com/CopticScriptorium/cts/blob/master/coptic/templates/index.html#L9  All text styles were adopted from the CopticScriptorium.org app. 

![default_view](https://cloud.githubusercontent.com/assets/2633382/7551843/771f668e-f665-11e4-8a8a-919e8ebd2d9a.png)

**Comment by ctschroeder** [comment]
preliminary wording provided.
