### ISSUE TITLE
Speed the search process by only returning HTML for selected visualizations

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#57]
From our emails: "2. Filtering and urn resolving process should be checked and streamlined: behind the spinning wheel, it looks like the system is pulling up a lot of corpora or documents before giving you the thing you requested."

**Comment by lukehollis** [comment]
Filtering and urn resolving is checked and streamlined and tested on several networks and devices at Harvard, my apartment, and two nearby coffee houses.  The system is only pulling up the minimum necessary to give you the thing you requested.

**Comment by ctschroeder** [comment]
@amir-zeldes should test, since it was hanging for him earlier this week.  Seems to be working ok for me in terms of response time.  (The accuracy of the filtering is addressed in other issues.)

**Comment by amir-zeldes** [comment]
Performance is good for me now.
