### ISSUE TITLE
Rename Search Field Ingest in Administrative interface

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#58]
From our emails: "3. Search Field Ingest: name should probably be changed to document metadata ingest or something like that (Amir, maybe you have a preferred title?)"
Amir's response: "3.      Any name is fine."

**Comment by lukehollis** [comment]
Because it is necessary to run the document metadata ingest after each document and visualization ingest, the Search Field Ingest has been included in the primary Ingest in the administrative interface.

**Comment by ctschroeder** [comment]
? so is the title changed or ...?

**Comment by lukehollis** [comment]
The search field ingest is now factored in to the one, primary ingest that handles everything. 
![ingests](https://cloud.githubusercontent.com/assets/2633382/7636989/bc7e2a40-fa38-11e4-9197-cf210022cdf6.png)

**Comment by ctschroeder** [comment]
ok, so there is no longer a thing called "search field ingest"?

**Comment by lukehollis** [comment]
Correct--because the document metadata ingest needed to rerun after each document ingest, they are included in one ingest.
