### ISSUE TITLE
Test Ingest on the remote host

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#59]
For now, all ingests should be run locally.  Further development here can happen after more updates on the javascript callback to be added by Thomas Krause and @amir-zeldes.

**Comment by lukehollis** [comment]
From @ctschroeder's email: "4. Remote ingest needs to be implemented and tested -- doesn't seem to
work right; also the visualizations were not quite right."

**Comment by ctschroeder** [comment]
Am not currently able to test on data.copticscriptorium.org BUT on coptic.aweb.io there is a problem:  It looks like the filtering system is using corpus level metadata, not document level.  One of the wrong Schroeder's in issue 22 https://github.com/CopticScriptorium/cts/issues/22 appears wrong ONLY on the corpus level metadata -- not on the document level.  This means the menu is filtering based on the wrong kind of metadata.

I think this may be a problem behind some of our other ingest issues.

**Comment by ctschroeder** [comment]
[sorry -- had not meant to relabel]

**Comment by lukehollis** [comment]
(Changing title since the ingest isn't split into two pieces anymore)

**Comment by lukehollis** [comment]
I created a staging environment for testing the ingest here: http://ec2-52-6-7-16.compute-1.amazonaws.com/  This will provide an environment for testing and manipulating data without having to change the production copy of our site. You can login there with the same credentials as the main data.copticscriptorium.org app.  Login at http://ec2-52-6-7-16.compute-1.amazonaws.com/admin. 

When you're ready to test the ingest, login and then create a new ingest at this link: http://ec2-52-6-7-16.compute-1.amazonaws.com/admin/ingest/ingest/add/  To start the ingest, simply click "Save" in the bottom right corner of the page.  

Would be happy to do a walk through on Skype / Hangouts to go over this issue in more depth as well.

**Comment by ctschroeder** [comment]
Thank you. I am in and out all day.  perhaps you and @amir-zeldes can connect? I know we will have a new corpus to include as of Monday or Tuesday.

**Comment by amir-zeldes** [comment]
OK, ingest is running.
