### ISSUE TITLE
Ingest HTML for different editions (such as MONB_YA, MONB_YB, MONB_ZC) or find a different way of resolving the URNs

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#6]

**Comment by lukehollis** [comment]
@amir-zeldes and @ctschroeder, this is a question we touched on briefly in our emails:  can I query ANNIS for HTML visualizations of different editions for the same corpus?  For instance, from Bridget's URNs: 
```xml
<work urn="urn:cts:copticLit:shenoute.A22" xml:lang="cop">
            <edition urn="urn:cts:copticLit:shenoute.A22.MONB_YA">
                <label xml:lang="eng">White Monastery Manuscript YA</label>
            </edition>
            <edition urn="urn:cts:copticLit:shenoute.A22.MONB_YB">
                <label xml:lang="eng">White Monastery Manuscript YB</label>
            </edition>
            <edition urn="urn:cts:copticLit:shenoute.A22.MONB_ZC">
                <label xml:lang="eng">White Monastery Manuscript ZC</label>
            </edition>
</work>
```
from [textinventory.xml](https://github.com/CopticScriptorium/cts/blob/master/inventory/textinventory.xml)

I have the work/corpus urn in place, but I'm unsure of how to resolve these editions to the ANNIS API currently.  It looks like the [two docnames listed for shenoute.a22 are both MONB.YA](https://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYTIy).  Thanks for your insight here!

**Comment by amir-zeldes** [comment]
Hi Luke,

 

These are not really different editions, they are simply different manuscripts containing parts of the same text. In the ANNIS context these are two completely distinct documents that happen to share a similar meta datum. As distinct documents, they should have distinct URNs as well. I’m not sure if this answers the question?

 

Amir

**Comment by ctschroeder** [comment]
Hi,

Yes. A22 is a conceptual text. There are multiple codices (MONB YA, YB, etc) with witnesses to the text. These codices are all fragmented. Resolving the URN for A22 should bring up all the witnesses/documents and their corresponding visualizations. 

Carrie

carrie@carrieschroeder.com

**Comment by lukehollis** [comment]
Thanks for the insight here with explaining the differences, @amir-zeldes and @ctschroeder!  I'm still not sure where to find the HTML to use for the different manuscripts.  

Here's how I query HTML for A22 YA517-518 from ANNIS:  
https://corpling.uis.georgetown.edu/annis/embeddedvis/htmldoc/shenoute.a22/YA517-518?config=norm

But using YB517-518 or ZC517-518 in the query to ANNIS doesn't work.  Where should I retrieve the HTML for the YB and ZC manuscripts?

**Comment by ctschroeder** [comment]
I think there is some misunderstanding about the structure of our data.  
Maybe we should Skype about it sometime this week. I am free 
midday/early afternoon tomorrow (11-4 Pacific ) and most of the day 
Thursday (9-5 Pacific).

On 3/17/15 5:00 PM, Luke Hollis wrote:
>
> Thanks for the insight here with explaining the differences, 
> @amir-zeldes <https://github.com/amir-zeldes> and @ctschroeder 
> <https://github.com/ctschroeder>! I'm still not sure where to find the 
> HTML to use for the different manuscripts.
>
> Here's how I query HTML for A22 YA517-518 from ANNIS:
>
> https://corpling.uis.georgetown.edu/annis/embeddedvis/htmldoc/shenoute.a22/YA517-518?config=norm
>
> But using YB517-518 or ZC517-518 in the query to ANNIS doesn't work. 
> Where should I retrieve the HTML for the YB and ZC manuscripts?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CopticScriptorium/cts/issues/6#issuecomment-82647473>.
>


-- 
________________________________
C. Schroeder
Associate Professor, Religious and Classical Studies
The University of the Pacific

carrie@carrieschroeder.com
http://www.carrieschroeder.com
https://pacific.academia.edu/CarolineSchroeder

Coptic SCRIPTORIUM
http://www.copticscriptorium.org

Blog
http://www.earlymonasticism.org

**Comment by lukehollis** [comment]
Okay, that sounds good!  I could do anytime after 12:30 tomorrow or anytime on Thursday.  Let me know what works best for you! 

I need to understand what materials URNs like urn:cts:copticLit:shenoute.A22.MONB_YA should show from ANNIS and from the repos.

**Comment by ctschroeder** [comment]
2 pm tomorrow Pacific time good?  Amir is teaching tomorrow, but I don't 
think we need him for this. This is about the data model really, I think.

On 3/17/15 6:13 PM, Luke Hollis wrote:
>
> Okay, that sounds good! I could do anytime after 12:30 tomorrow or 
> anytime on Thursday. Let me know what works best for you!
>
> I need to understand what materials URNs like 
> urn:cts:copticLit:shenoute.A22.MONB_YA should show from ANNIS and from 
> the repos.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CopticScriptorium/cts/issues/6#issuecomment-82663339>.
>


-- 
________________________________
C. Schroeder
Associate Professor, Religious and Classical Studies
The University of the Pacific

carrie@carrieschroeder.com
http://www.carrieschroeder.com
https://pacific.academia.edu/CarolineSchroeder

Coptic SCRIPTORIUM
http://www.copticscriptorium.org

Blog
http://www.earlymonasticism.org

**Comment by balmas** [comment]
Let me know if there is anything you need from me on this.

**Comment by amir-zeldes** [comment]
Ditto, I'm teaching Wednesday, but I'll look at my e-mail after if questions arise.

**Comment by lukehollis** [comment]
Okay, 2 PM Pacific time tomorrow sounds good!  I only need to know what resources I should display for those URNs with the MONB_YB, MONB_ZC, etc.  So when you put in the urn:cts:copticLit:shenoute.A22.MONB_YB URN to the input field in the header, what should happen?

**Comment by ctschroeder** [comment]
@balmas thanks for offering!  Let's plan Google Hangout at 2 pm Pacific/5 PM Eastern for sure with Luke and me. Bridget, if you want to join we always appreciate your expertise, but no worries if it's a bad time.
Luke:  those MONB.* names all refer to manuscript sigla from the White Monastery in Egypt.  Think of them like library systems:  the dewey decimal system for White Monastery manuscripts.  In ANNIS, this appears in the metadata msName.  So you should have MONB.EG in the apophthegmata patrum, MONB.YA, YB, XL, and more in both Abraham Our Father and Acephalous work 22.  I will explain more tomorrow.  But basically you're looking for msName in the ANNIS, TEI, PAULA metadata.  (E.g., line 22 here in the TEI https://github.com/CopticScriptorium/corpora/blob/master/abraham/shenoute.abraham.our.father_TEI/Abraham.YA518-520_TEI.xml)

**Comment by lukehollis** [comment]
Yes, this all makes sense, but I don't know where to find the HTML, TEI, or ANNIS data for MONB_YB and MONB_ZC.  I've only been able to find data for MONB_YA for shenoute.A22.  From the TEI: https://github.com/CopticScriptorium/corpora/tree/master/shenoute-a22/shenoute.a22_TEI.  From ANNIS (https://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYTIy), the document names are YA517-518 and YA421-428.  I understand that how they're different but don't know where to find the resources for the different versions.  What should I ingest and resolve to for MONB_YB and MONB_ZC?

**Comment by ctschroeder** [comment]
We don't have documents from YB and ZC yet.  They are coming soon.

You should use the rest API from ANNIs to find all the msName's we have 
currently.  MONB.YA is in A22 and also Abraham.

TEI will be in the TEI subdirectory for each repository.  I can explain 
and show you tomorrow.  This is a complex class of data.

Take care,
Carrie

On 3/17/15 8:56 PM, Luke Hollis wrote:
>
> Yes, this all makes sense, but I don't know where to find the HTML, 
> TEI, or ANNIS data for MONB_YB and MONB_ZC. I've only been able to 
> find data for MONB_YA for shenoute.A22. From the TEI: 
> https://github.com/CopticScriptorium/corpora/tree/master/shenoute-a22/shenoute.a22_TEI. 
> From ANNIS 
> (https://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYTIy), 
> the document names are YA517-518 and YA421-428. I understand that how 
> they're different but don't know where to find the resources for the 
> different versions. What should I ingest and resolve to for MONB_YB 
> and MONB_ZC?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CopticScriptorium/cts/issues/6#issuecomment-82729365>.
>


-- 
________________________________
C. Schroeder
Associate Professor, Religious and Classical Studies
The University of the Pacific

carrie@carrieschroeder.com
http://www.carrieschroeder.com
https://pacific.academia.edu/CarolineSchroeder

Coptic SCRIPTORIUM
http://www.copticscriptorium.org

Blog
http://www.earlymonasticism.org

**Comment by lukehollis** [comment]
Okay, terrific, that makes sense!  Thanks so much for your help with this, and I'll talk to you soon!

**Comment by lukehollis** [comment]
Opened a new issue to find msNames from ANNIS here: https://github.com/CopticScriptorium/cts/issues/43

There's a ticket for the Github repo structure here:
https://github.com/CopticScriptorium/cts/issues/38

For me, this ticket was mostly just for my question on why I couldn't find data for YB or ZC.  I think after our call today, it should be able to be closed.

**Comment by lukehollis** [comment]
All the msNames are ingested from ANNIS and displayed on the document URNs.  
![msnames](https://cloud.githubusercontent.com/assets/2633382/6762763/01dd6848-cf3d-11e4-83e4-66fa5bb7305f.png)

**Comment by ctschroeder** [comment]
Ok. Thanks.  I need to look at the table of URNs. Something is not quite right. Corpus should just be ap. Not the saying #. 

carrie@carrieschroeder.com

**Comment by lukehollis** [comment]
The inventory of URNs I'm referencing is from Bridget's work here: https://github.com/CopticScriptorium/cts/blob/master/inventory/textinventory.xml

with
```
    <textgroup urn="urn:cts:copticLit:ap">
        <groupname xml:lang="eng">The Apophthegmata Patrum</groupname>
        <work urn="urn:cts:copticLit:ap.001" xml:lang="grc">
            <title xml:lang="eng">The Apophthegmata Patrum</title>
            <edition urn="urn:cts:copticLit:ap.001.MONB_EG">
                <label xml:lang="eng">White Monastery Manuscript EG</label>
            </edition>
        </work>
    </textgroup>
```

**Comment by ctschroeder** [comment]
Yes. We also had a thread for the AP urns specifically in which we either modified them or I said to check back when doing them, since this corpus was particularly strange. There is also something strange about Abraham. Do you have a fully up to date table, including the relANNNIS paths, and anything else that has been modified?  Thanks. 

carrie@carrieschroeder.com

**Comment by ctschroeder** [comment]
making a note here about this issue: https://github.com/CopticScriptorium/cts/issues/50

**Comment by ctschroeder** [comment]
Ok, I this is working.
