### ISSUE TITLE
Add a field to the HTML visualization format for button

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#61]
From our emails: "6. In the Django administration, have diferrent fields for the the names on the visualization button (abbreviated), slug (abbreviated), and visualization title (full "Diplomatic transcription"/"Normalized text"/"Linguistic analysis" that appears above the actual visualization)"

**Comment by lukehollis** [comment]
This field is added and implemented in the templates:
![button_title](https://cloud.githubusercontent.com/assets/2633382/7633932/a4beed58-fa25-11e4-91b2-19da905484c3.png)

**Comment by ctschroeder** [comment]
I tried to change the labels a few days ago, and it didn't stick.  Do you know why?

**Comment by ctschroeder** [comment]
Looks like it is working now.  I just changed the buttons.
