### ISSUE TITLE
Decide how best to integrate the resolver application with the copticscriptorium.org domain

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#62]
From our emails: "7. Luke needs to check wiht Bridget about how to implement the data model with respect to the paths, because as they are right now, they don't resolve, and it's not clear they could resolve when we migrate to our site.  [To test it before migration, you might want to replace copticscriptorium.org with coptic.aweb.io].  But consult with Bridget before doing anything."

**Comment by lukehollis** [comment]
@balmas I'll send a better email about this, but one possibility that I wanted to ask you about was hosting the django app on a subdomain like cts.copticscriptorium.org and entering a htaccess rule on the primary copticscriptorium.org domain to forward anything like http://copticscriptorium.org/urn:.* to the resolver.  Would benefit from your insight here.

**Comment by balmas** [comment]
Hi @lukehollis, that seems like a reasonable approach to me, and is pretty analagous to how I deal with the Perseus data.perseus.org URLs+URNs.  It might be useful to take a look at http://linkeddatabook.com/editions/1.0/#htoc11 (if you haven't already) and http://sites.tufts.edu/perseusupdates/beta-features/perseus-stable-uris/ (which talks about how we've implemented the HTTP redirect and response codes on Perseus)

**Comment by lukehollis** [comment]
Thanks for insight, @balmas! This sounds great.  Those resources combined with your previous notes about the redirects in the Coptic Scriptorium Data Model Analysis provide good direction here.  I'll send a better email to the group in a few moments.

**Comment by lukehollis** [comment]
It appears that the Github hosting used for Copticscriptorium.org doesn't allow for the htaccess rules okayed in our emails:
 
<IfModule mod_alias.c>
RedirectMatch 303 ^/urn(.*)$ http://data.copticscriptorium.org/urn$1
</IfModule>

Rather, Github suggests to use the Jekyll redirect from plugin, as mentioned in this article: https://help.github.com/articles/redirects-on-github-pages/

Since the copticscriptorium.org files are also on Bluehost and Bluehost supports htaccess rules, we could easily use their hosting instead of github and add the approved htaccess rules there as one potential alternative to implementing the Jekyll redirect from plugin.

**Comment by ctschroeder** [comment]
done -- moved to AWS; subdomain registered with Bluehost data.copticscriptorium.org directed with an A record to the AWS server
