### ISSUE TITLE
Rework visual components for the banner/logo and URN box

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#63]
From our emails: "8. Banner will be shortened with URN box on the right rather than underneath."

**Comment by lukehollis** [comment]
I can definitely implement this if you send the new banner my way--or you can change the HTML templates here: https://github.com/CopticScriptorium/cts/blob/master/coptic/templates/header.html#L19

**Comment by ctschroeder** [comment]
We shouldn't need a new banner.  You should be able to just move the box up.  The banner is not a solid banner -- it's several individual image files strung together.  Add the box.

I tried to experiment with it but couldn't see the implementation -- didn't look like it was going on either data.copticscriptorium.org or coptic.aweb.io. 

Alternatively you could put the URN box in your brown menu bar with all the

**Comment by lukehollis** [comment]
I'm unclear of which direction you would like the banner shortened and need a little more information about what you mean by "move the box up".  Are you meaning that you want the URN resolver input field that says "Enter URN..." inline with the other header logos?

**Comment by ctschroeder** [comment]
My answer was going to be to just refer to our conversation on Skype 
Monday, but the nav bar situation changes things.  We need links to 
home, documentation, and about.  And the URN box should go to the right 
of the banner or on your lower query bar with corpus, annotation, etc.  
If you have a design rec, please suggest it. Otherwise I need to sleep 
on it.

**Comment by ctschroeder** [comment]
After thinking about it today, I think we should stick with the plan we discussed over Skype.  The box that says "enter URN" just needs to move up and the width of the logo section should decrease.

**Comment by ctschroeder** [comment]
looks good!
