### ISSUE TITLE
What to name the URN listed as "Passage" in the "Cite this Document" section

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#64]
Also related to this issue from our emails: "8. Luke needs to check with Bridget about what that URN listed as "Passage" in the "Cite This Document" section should be called; it's definitely not "passage" and is more like "edition" or "expression" or document or something like that."

**Comment by balmas** [comment]
In CTS terms it would be "edition" (or "translation" for those works which aren't originally coptic, such as the bible).  In LAWD terms it's "Written Work" (or the more specific "Translation")

**Comment by lukehollis** [comment]
Okay, good deal--I'll update this in the copy for the Cite this Document section.

**Comment by ctschroeder** [comment]
So, are we going with "Written Edition or Translation"?

**Comment by lukehollis** [comment]
From our talk on Monday, we decided to use "Edition", and this is now implemented:
![edition](https://cloud.githubusercontent.com/assets/2633382/7633898/69c43e10-fa25-11e4-8bd1-05a34123f1c9.png)
