### ISSUE TITLE
Check corpus metadata fields so they are internally consistent

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#65]
From our emails: "9. Carrie and Amir need to check corpus metadata fields so they are internally consistent (some debate over making the corpus titles verbose (Abraham Our Father) or abbrevaited like the urns (shenoute.abraham)"

**Comment by lukehollis** [comment]
Related from our emails: "10. (Carrie and Amir need to check the other metadata for internal
consistency as well.)"

**Comment by ctschroeder** [comment]
have been waiting on this since it's been unclear if we needed to make other metadata changes, and it is very time consuming to publish the corpora multiple times.
