### ISSUE TITLE
Rewrite Ingest to watch for DOM manipulation / "loaded-embedded-vis" class

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#68]
Ingest should be rewritten to address new updates by Thomas Krause to the document HTML visualization with Vaadin, watching for DOM manipulation and the "loaded-embedded-vis" class added to the "v-app" div element.

**Comment by lukehollis** [comment]
This change has been implemented with a similar class, though I did not find the loaded-embedded-vis class.  This speeds the ingest process.

**Comment by ctschroeder** [comment]
@amir-zeldes will have to look at this
