### ISSUE TITLE
Corpus level urns are inaccurate

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#69]
Corpus level URNs listed on the results pages are not accurate.  
![screen shot 2015-05-14 at 9 04 27 am](https://cloud.githubusercontent.com/assets/4079217/7635831/4464e514-fa18-11e4-80e0-8fba41dc0e97.png)
The URN listed above should return ALL editions of the Gospel of Mark, not just the manually edited ones.  But it is being displayed as if it were the URN for just the manually edited chapters of Mark.

Likewise this URN is incorrect:
![screen shot 2015-05-14 at 9 06 00 am](https://cloud.githubusercontent.com/assets/4079217/7635861/787d02b4-fa18-11e4-9a03-69b48c1d9cc5.png)

I am now checking all of them and will list them in the thread. Use the URNs in the inventory Bridget provided that are just above the document level urns in the hierarchy.

**Comment by ctschroeder** [comment]
Likewise: urn:cts:copticLit:nt.1cor should be urn:cts:copticLit:nt.1cor.sahidica_ed
![screen shot 2015-05-14 at 9 19 59 am](https://cloud.githubusercontent.com/assets/4079217/7636188/6df498c8-fa1a-11e4-930f-5c78578502a3.png)

**Comment by ctschroeder** [comment]
The URN urn:cts:copticLit:nt is being listed next to the unedited NT corpus name. This is misleading.  The URN urn:cts:copticLit:nt should resolve to ALL New Testament documents, whether they are in the unedited corpus, edited corpus, or anyhwere -- that is the URN for any Coptic New Testament document anywhere.  It is not a unique identifier for the corpus.

This needs to be fixed. @amir-zeldes created subcorpora in the big NT corpus for precisely this reason.  You should use URNs for the subcorpora.  so urn:cts:copticLit:nt.1cor.sahidica is the URN for all documents from 1 Corinthians in the unedited sahidica.nt corpus.

There is NO urn for the corpus.  Only for each book of the bible.

**Comment by lukehollis** [comment]
I've updated the URNs for the Gospel of Mark and 1 Corinthians. Let me know what you'd prefer to have listed next to the New Testament title--for the moment, I've hidden the "urn:cts:copticLit:nt" next to the title.

**Comment by ctschroeder** [comment]
Great.  That's the right choice.  It's possible to list a urn for the subcorpora, but this is fine for now.
