### ISSUE TITLE
Fix bug with displaying manifest from the JSON API

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#7]

**Comment by lukehollis** [comment]
Fixed: JSON api manifest available at http://coptic.aweb.io/api/manifest/

**Comment by lukehollis** [comment]
The JSON api manifest displays as expected, and this ticket is ready to be closed.

**Comment by ctschroeder** [comment]
Link above does not work.

**Comment by ctschroeder** [comment]
Link above does not work.

**Comment by lukehollis** [comment]
Here's the updated link:  http://data.copticscriptorium.org/api/manifest

**Comment by ctschroeder** [comment]
This is looking good.
