### ISSUE TITLE
Large, unedited Sahidica corpus is missing from dropdown

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#70]
Documents from the large, unedited Sahidica NT corpus are appearing in the results after using the menu filters, but the corpus is not listed in the filter itself.  What's going on with the ingest to get this situation?  Thanks.
![screen shot 2015-05-14 at 9 08 26 am](https://cloud.githubusercontent.com/assets/4079217/7635924/d0c8becc-fa18-11e4-9e89-f4209c9e5354.png)

**Comment by lukehollis** [comment]
The documents in the large, unedited Sahidica NT corpus do not contain a metadata field called "corpus" in ANNIS, so they're not included in this document metadata search field.   

For reference, an example single document in the Sahidica NT corpus: http://corpling.uis.georgetown.edu/annis-service/annis/meta/doc/sahidica.nt/Matthew_26

Or all of the document metadata for that corpus here: http://corpling.uis.georgetown.edu/annis-service/annis/meta/doc/sahidica.nt

Here's an example of the "corpus" metadata field from shenoute.a22:

```
<annotation>
<annotationPath>a22.YA421-428</annotationPath>
<annotationPath>shenoute.a22</annotationPath>
<corpusName>a22.YA421-428</corpusName>
<name>corpus</name>
<pre>21843</pre>
<type>DOCUMENT</type>
<value>shenoute.a22</value>
</annotation>
```
(retrieved via http://corpling.uis.georgetown.edu/annis-service/annis/meta/doc/shenoute.a22)

**Comment by ctschroeder** [comment]
?? they all have a subcorpus field (e.g., Matthew or 2_Timothy below) and all have the same corpus field of sahidica.nt
```
<annotation>
<annotationPath>Matthew_24</annotationPath>
<annotationPath>Matthew</annotationPath>
<annotationPath>sahidica.nt</annotationPath>
<corpusName>Matthew_24</corpusName>
<name>chapter</name>
<pre>21590</pre>
<type>DOCUMENT</type>
<value>24</value>
</annotation>
<annotation>
<annotationPath>2_Timothy_4</annotationPath>
<annotationPath>2_Timothy</annotationPath>
<annotationPath>sahidica.nt</annotationPath>
<corpusName>2_Timothy_4</corpusName>
<name>chapter</name>
<pre>21282</pre>
<type>DOCUMENT</type>
<value>4</value>
</annotation>
```

**Comment by lukehollis** [comment]
The corpus search field is populated by an <annotation> element with a child <name>corpus</name> element on the other documents that aren't in the sahidica NT corpus.

**Comment by ctschroeder** [comment]
@amir-zeldes  will add corpus metadata to the large Sahidica corpus in ANNIS.  (one of us needs to do it in the base data files)

**Comment by amir-zeldes** [comment]
Sorry, mea culpa, that corpus really didn't have the corpus metadatum on the documents. I've fixed it and re-imported, and the Excel version is also up to date for next conversion.

**Comment by ctschroeder** [comment]
@lukehollis can you see if this works properly now on a new ingest?  Thanks. Removing "metadata" label.

**Comment by lukehollis** [comment]
I'm seeing a corpus field now, but it looks like some of the corpus values are incorrect.  One example is 1st Corinthians 1, where the annotation for "corpus" is set to "apophthegmata.patrum": http://corpling.uis.georgetown.edu/annis-service/annis/meta/doc/sahidica.nt/1_Corinthians_1

**Comment by ctschroeder** [comment]
@amir-zeldes ?

**Comment by amir-zeldes** [comment]
This should be fixed now, sorry about the error.

**Comment by ctschroeder** [comment]
thanks!
