### ISSUE TITLE
Filter for corpus Sahidica.1cor produces inaccurate results

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#72]
Chapter 1 is missing from the document result list.

**Comment by lukehollis** [comment]
This is related to the sahidica.mark metadata value in ANNIS from https://github.com/CopticScriptorium/cts/issues/71.

(reference http://corpling.uis.georgetown.edu/annis-service/annis/meta/doc/sahidica.1corinthians/1Cor_01)

**Comment by ctschroeder** [comment]
metadata is incorrect -- needs to be changed.

**Comment by ctschroeder** [comment]
fixed metadata -- ready for republication and re-ingest.
