### ISSUE TITLE
top nav bar not updating

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#73]
The nav bar should be linked to the main nav bar on the main site, so that whenever the nav bar on the main site gets updated, this nav bar is updated as well.  You can look at the code we use to do this on our website page.  
Here is the nav bar https://github.com/CopticScriptorium/CopticScriptorium.github.io/blob/master/nav.html

Here is the index page, which calls the nav bar https://github.com/CopticScriptorium/CopticScriptorium.github.io/blob/master/index.html

**Comment by lukehollis** [comment]
In order to load the HTML for the nav bar in the same way that the copticscriptorium.org site does it with javascript, we'd have to enable cross-origin resource sharing on the server hosting the nav.html file, but unfortunately Github hosting doesn't allow for enabling cross-origin resource sharing.

**Comment by ctschroeder** [comment]
Ok, understood. This is probably something worth mentioning before. 
Given that, I think we should have a simplified menu  that just leads to 
home, documentation, about.  This is also related to the logos and 
placement of the URN, so I need to sleep on it.

**Comment by ctschroeder** [comment]
that is unfortunate, since we have wanted the same nav bar across the site without having to check each page everyone we update. I wish this had been mentioned when the nav bar was implemented on this module. What are the other options?

**Comment by ctschroeder** [comment]
sorry, that comment was NOT supposed to post.  Long night.

**Comment by lukehollis** [comment]
I'm sorry if I missed something, but was importing the nav.html via javascript listed in our other tickets and emails about the visual appearance?  I referenced your email from March 20th in this ticket on visual updates if it's useful to keep thinking about this area: https://github.com/CopticScriptorium/cts/issues/15

**Comment by ctschroeder** [comment]
In my experience, when a feature is requested, it is mentioned if the functionality of that feature can't be implemented.  I also notice in that thread that in response to the identical situation with the footer, you were going to think about the functionality further.  This is not a deal breaker--this is just me saying it would have been helpful to bring up at implementation, since it's clear in our website design what the nav bar is doing. And it wasn't possible for me to know this unless I changed the nav bar or looked at the source code.

**Comment by ctschroeder** [comment]
For now please leave it as is--I still haven't figured out a good design.  Thanks

**Comment by ctschroeder** [comment]
For now, @ctschroeder will manually update the nav bar.  Until we decide how to deal with this in a better way.
