### ISSUE TITLE
filtering for translator is way off

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#75]
Filtering for Antony Alcock as translator pulls up many many more documents and even more corpora than he is affiliated with.  I do not think this is just an issue of ingesting corpus metadata instead of document.  Alcock is only on ONE document, so I don't know what is going on here.

**Comment by lukehollis** [comment]
I fixed a bug with calculating the splittable search field (after the ingest has already run), and Antony Alock now pulls up the appropriate document on data.copticscriptorium.org.

**Comment by ctschroeder** [comment]
Great that this is fixed.  There's still a problem with other metadata though.  https://github.com/CopticScriptorium/cts/issues/54

**Comment by ctschroeder** [comment]
this seems to be fixed.
