### ISSUE TITLE
Add button to search corpus in ANNIS in document view

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#77]

**Comment by ctschroeder** [comment]
The “Search ANNIS” button on the corpus level needs to be added on the document views somewhere -- CTS recommends under the six existing buttons.  “Search entire corpus in ANNIS” + Search ANNIS button or something like that [The link to the ANNIS UI at the bottom of the document view already does this - we just need to copy that link into an extra button at the top; should be easy - AZ]

**Comment by dcbriccetti** [comment]
This is in a new branch called “testing”, which we can run on the test server (later today).

**Comment by dcbriccetti** [comment]
Running on test server now. http://52.39.198.200/
