### ISSUE TITLE
Add CTS URNs to the manifest in the JSON API

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#8]

**Comment by lukehollis** [comment]
The json manifest is available here: http://coptic.aweb.io/api/manifest/  It contains all of the information in the database for the URN resolver, and this ticket is ready to be closed.

**Comment by ctschroeder** [comment]
Thanks for creating this.  Most API manifest's I've seen are a little more human readable because of line breaks and such.  Am I misremembering, or is there a way to make this slightly more legible?  Many thanks.

**Comment by lukehollis** [comment]
The api manifest is now updated to be more human-readable.

**Comment by ctschroeder** [comment]
Link above does not work.

**Comment by lukehollis** [comment]
Here's the new link for the manifest: 
http://data.copticscriptorium.org/api/manifest
and URNs:
http://data.copticscriptorium.org/api/urns

**Comment by ctschroeder** [comment]
Does the manifest automatically update?  I changed the titles for the buttons, and I don't see the new titles on the manifest --just the old ones.

**Comment by lukehollis** [comment]
The manifest does automatically update--are you changing the HTML Visualization Format titles on the copy of the site at data.copticscriptorium.org instead of the coptic.aweb.io staging site?  http://data.copticscriptorium.org/admin/texts/htmlvisualizationformat/

**Comment by ctschroeder** [comment]
ah, sorry, I was changing on the coptic.aweb.io site.  am now testing 
etc on the data.copticscriptorium.org site

**Comment by ctschroeder** [comment]
Thanks.  I had a chance to look this morning.  There is something strange with the urn manifest.  Looks like the paths are taking the titles not slugs for the visualizations.  Also there are strange spaces in some of them.  See for example:
```
            "urn:cts:copticLit:nt.mark.sahidica_ed: 3",
            "urn:cts:copticLit:nt.mark.sahidica_ed: 3/Sahidica Chapter View/html",
            "urn:cts:copticLit:nt.mark.sahidica_ed: 3/tei/xml",
            "urn:cts:copticLit:nt.mark.sahidica_ed: 3/paula/xml",
            "urn:cts:copticLit:nt.mark.sahidica_ed: 3/relannis",
            "urn:cts:copticLit:nt.mark.sahidica_ed: 3/annis",
```
Also, does the URN list update automatically?  Thanks so much.

**Comment by lukehollis** [comment]
Ah, looks like I had to restart apache on the server for these changes to take affect.  I'm currently seeing the slugs for the URNs.

**Comment by lukehollis** [comment]
Yes, the URN list updates automatically with metadata from ANNIS.

**Comment by ctschroeder** [comment]
The slugs look good.  
1. There is still a space in those mark chapter three urns 
2. Something weird is going on with ap.53 and there are no bible urns now
3. Does this mean we have to restart the server every time we update?  This seems excessive. What is the solution?  
Thanks!
