### ISSUE TITLE
Filtering by menu items ("or" within a field, "and" between fields)

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#81]
Filtering is still in "or" mode:  change to “or” within a field and “and” between fields 
[This is complicated by the fact that the DB is created by Django migrations and accessed using Django functions that hide the SQL; either use appropriate Django accessors to implement this, or fetch the different filtered list and run the intersection of the ‘and’ criteria in code post SQL; I think running direct SQL to the DB is a bad idea since Django might be used to modify the schema and this function would be wise to it - AZ]

**Comment by ctschroeder** [comment]
Possibly in this code: https://github.com/CopticScriptorium/cts/blob/master/coptic/api/views.py

**Comment by amir-zeldes** [comment]
Implemented in #89
