### ISSUE TITLE
Besa visualizations not functioning properly

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#82]
More detail in this review document. https://docs.google.com/document/d/1Wf5lDjJKa_hAgU2SCZ9daBUk7sLMwRy80I7rR9W4opg/edit?usp=sharing
[seems to be an inability to render webkit transforms (only the Besa corpus contains them, used for the thin long Fais), not sure why and how the table cells get distorted as a result; needs debugging - AZ]

**Comment by amir-zeldes** [comment]
The Besa corpus is the only one in which we have tall thin letters, encoded with the CSS selector [rend*="long"]. When this is matched, we apply -webkit-transform: scale(0.7, 1.6) and similarly transform etc. This works fine in ANNIS:

https://corpling.uis.georgetown.edu/annis/embeddedvis/htmldoc/besa.letters/to_aphthonia?config=dipl 

But in the Django app, starting on page 4 of the manuscript you’ll see the error with the td width:

http://data.copticscriptorium.org/texts/to_aphthonia/to_aphthonia/dipl

**Comment by dcbriccetti** [comment]
Is the problem the extra width?

<img width="815" alt="screen shot 2016-03-19 at 11 10 18 am" src="https://cloud.githubusercontent.com/assets/55099/13900436/70483fb0-edc3-11e5-921b-aa4c314f34e8.png">

Does this fix it, or is there something more?

<img width="376" alt="screen shot 2016-03-19 at 11 11 02 am" src="https://cloud.githubusercontent.com/assets/55099/13900438/7eab68ac-edc3-11e5-806c-c246faa9a1c5.png">

In Chrome Developer Tools, I disabled the width: 500px to see the effect.

div.htmlvis span {
  font-family: antinoouRegular, sans-serif;
  width: 500px;
  white-space: normal !important;
}

**Comment by amir-zeldes** [comment]
Yes, the column width and the floating letter in the middle are the problem. It's possible setting the width fixes it, though I'm still not sure why the transform instruction works while embedded in ANNIS but not in the cts repo. Did you manually add width 500? The original stylesheet doesn't give an instruction width 500 (or div.htmlvis span for that matter), though it might be inherited. Here's the original CSS generating this:

https://github.com/CopticScriptorium/corpora/blob/master/besa-letters/besa.letters_relANNIS/ExtData/dipl.css

**Comment by dcbriccetti** [comment]
Possible fix is now on the test server. Let’s monitor for unwanted side effects.
http://52.36.1.55/texts/besa_letters/to_aphthonia/dipl (may need “shift-reload” or cache clear to update CSS).

**Comment by ctschroeder** [comment]
Looks good so far.  Checked a couple other docs to be sure, as well.

**Comment by amir-zeldes** [comment]
It looks fine to me too, but I'd like to understand the mechanism here: As far as I can tell, the line with:

```
width: 500px;
```

doesn't actually occur in the css stylesheet fed to ANNIS for this corpus. In the original it reads:

```
.htmlvis {
font-family: Antinoou, sans-serif;
counter-reset: line 0;
}
div.copt_line[line="1"]{text-indent:20px;}
...
```

Are you seeing the 500px on ingestion from ANNIS? Is this something that the ANNIS visualizer implants? Maybe from some VAADIN container div? Did you delete this line locally now or is it gone from the ingestion? 

I'm basically trying to understand if we can expect this to recur, and whether anything needs to be done in the original css file uploaded to ANNIS.

Thanks!

**Comment by amir-zeldes** [comment]
In fact, it just occurred to me but you can see the input CSS that ANNIS is getting right here:

https://github.com/CopticScriptorium/corpora/blob/master/besa-letters/besa.letters_ANNIS/ExtData/dipl.css

**Comment by dcbriccetti** [comment]
It came from a Coptic Scriptorium stylesheet, not from Annis.
<img width="1058" alt="screen shot 2016-05-06 at 12 44 19 pm" src="https://cloud.githubusercontent.com/assets/55099/15084467/86a972ca-1388-11e6-8c64-54f8d146f7e9.png">

**Comment by amir-zeldes** [comment]
That's strange... I thought I saw the instruction was applied to a class called ".htmlvis" - that's the class ANNIS assigns to the container for the visualizer. It's possible the previous developer misused this in some way and hardwired something to the same class name I guess... In any case, you're saying this shouldn't come back, right?

**Comment by dcbriccetti** [comment]
You can see here
https://github.com/CopticScriptorium/cts/commit/d488025a1fd81d1753878beb7cefc9c48aed727c
that the width I removed applies to all **spans** within htmlvis divs.

**Comment by amir-zeldes** [comment]
Yes, I see, I'm just wondering where it came from to begin with. As I was saying, the original css that leads to this visualization has no instruction like that (for span, or any other element really):

https://github.com/CopticScriptorium/corpora/blob/master/besa-letters/besa.letters_ANNIS/ExtData/dipl.css

But if it'll work in production I guess we can just forget about this mystery :) 

It's not in production yet, right? I'm still seeing the problem, even after empty cache+hard reload.

**Comment by dcbriccetti** [comment]
I have no idea where the CSS came from. There’s a lot of it.

Right, it’s not in production. The CSS being poorly understood, I wanted to watch for harmful side effects of the change.

**Comment by amir-zeldes** [comment]
OK, if nothing turns up, feel free to deploy. Thanks!
