### ISSUE TITLE
Metadata fields with URLs show code not links

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#83]
In the visualizations, the license field in the metadata is showing our url code [need to add functionality to recognize and parse URL if a metadatum contains it -AZ]

e.g. see http://data.copticscriptorium.org/texts/to_thieving_nuns/to_thieving_nuns

**Comment by dcbriccetti** [comment]
This one turns out to be quite easy.
https://github.com/CopticScriptorium/cts/commit/9345c57021c0e0fcf34f4fbacb249b344d6e45f6

**Comment by ctschroeder** [comment]
Hmm.  I'm not seeing links, just flat text:
<img width="1153" alt="screen shot 2016-03-31 at 9 27 47 pm" src="https://cloud.githubusercontent.com/assets/4079217/14197794/7c401612-f787-11e5-9056-140812aa79b9.png">

There should be a link each in the license and Greek_source metadata fields.

**Comment by ctschroeder** [comment]
mostly fixed.  CSS needs to be adjusted, and then this can be closed. Thanks, Dave!

**Comment by ctschroeder** [comment]
fixed-yeah!
