### ISSUE TITLE
Besa repository structure needs clarification

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#85]
Besa is treated as one corpus in ANNIS and two in the resolver; this needs discussion, a decision, and debugging after the decision.  It could be treated like the AP (one corpus for multiple works) or like the Shenoute material (one corpus for each work); it is currently treated like the AP in ANNIS.  The repo code will need changing, because the Besa repository is currently hardwired as an exception in the code.  Whatever we decide, we should debug the code to get rid of the exceptions baked in for the Besa corpus.

**Comment by ctschroeder** [comment]
Decided to make the Besa corpus in data.copticscriptorium.org to be like the AP -- one corpus of Besa's letters.  @ctschroeder will do this late April/early May

**Comment by ctschroeder** [comment]
I don't think we need to do anything other than delete the repos and create a new one, but we should check: @dcbriccetti is there anything in the code that is specific to Besa?

**Comment by dcbriccetti** [comment]
There’s this code in ingest.py, which I never took the time to fully understand:

```
for corpus in Corpus.objects.filter ...
    for title, in get_selected_annotation_fields ...
        # Add exception for besa.letters corpus in ANNIS
       if corpus_name == "besa.letters" and title != corpus.slug:
            continue
```

**Comment by ctschroeder** [comment]
Hmm.  I will look and see what I can do on the test server. If what I 
need doesn't work, I may ask you to delete this exception aas a test.  
Thanks!

**Comment by ctschroeder** [comment]
It looks like we can't add a new corpus for all of Besa's letters due to that exception.  The [helper python script](https://github.com/CopticScriptorium/cts/blob/19b67bdba0b724362c2c7ad85478b0f43917d35c/scripts/helper.py) also contains references to Aphthonia and Thieving Nuns as specific corpora, but I don't think we use that for anything unless we are setting up a fresh database instance or something.
I request/recommend we try eliminating the exception Dave pointed to above, deploying the code on the test server, and trying to set up the new Besa corpus.  
@dcbriccetti do you think you could try that?  If it will be a while, let me know.  (Amir, if we can't get this sorted soon, then I will add a third corpus for So's new letter so we at least can get it online.)

**Comment by dcbriccetti** [comment]
I removed the special besa logic from ingest.py, and that’s running on the test server now.

**Comment by ctschroeder** [comment]
Score: http://52.36.1.55/filter/author=35509:Besa

Thanks!

**Comment by ctschroeder** [comment]
So you can put it on the main server @dcbriccetti.  Thanks again

**Comment by dcbriccetti** [comment]
Done. You’re very welcome.

**Comment by ctschroeder** [comment]
All set: http://data.copticscriptorium.org/urn:cts:copticLit:besa
