### ISSUE TITLE
Show only the appropriate download format buttons, and have them lead to the correct subdirectory

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#86]
1. Need fields for the download formats so that the buttons for each download format appear ONLY if that download format is available.  Currently all three buttons (TEI, PAULA, relANNIS) appear for all corpora, even if a corpus doesn’t have all three formats available (e.g. machine-only annotated Sahidica).  

2. Also buttons all go to the same place; each one should go to the subdirectory on GitHub for that set of documents (e.g., the TEI button takes you to TEI subdirectory of that corpus’s directory in the public Corpus GitHub repository).

**Comment by dcbriccetti** [comment]
Is it sufficient to determine which formats are present on GitHub once, at ingestion time, or must we check more often?

**Comment by ctschroeder** [comment]
I believe once at ingestion is fine, but I defer to @amir-zeldes. 

This is also lower priority than the other issues with high priority labels.

**Comment by amir-zeldes** [comment]
Only on ingest is fine (we'd just need to reingest that one corpus)

**Comment by dcbriccetti** [comment]
![screen shot 2016-05-27 at 12 13 01 am](https://cloud.githubusercontent.com/assets/55099/15600606/e034a068-239f-11e6-9bf7-ff0e34dc44c3.png)

After selecting a text:
![screen shot 2016-05-27 at 12 14 16 am](https://cloud.githubusercontent.com/assets/55099/15600630/04c37de6-23a0-11e6-8ab8-088fd974b9ee.png)

**Comment by dcbriccetti** [comment]
This is on the test server now.
http://52.39.198.200/

**Comment by amir-zeldes** [comment]
Filters don't work for me on the test server just now, for some reason (nothing happens when I click one)

**Comment by dcbriccetti** [comment]
Odd. I can’t reproduce. Clear cache? Restart browser? JavaScript enabled? Browser plugins interfering?
What’s your OS and browser?

**Comment by amir-zeldes** [comment]
Empty cache and hard reload solved it (Chrome Win7-64). It's possible I just didn't wait long enough the first time, and/or it hanged. I see there's no spinning 'progress' icon anymore, so it's hard to tell if it's doing something - even a textual "loading..." might be helpful for users to identify feedback after clicking.

**Comment by dcbriccetti** [comment]
Amir, you might review the commit just above and see if you like the approach. The corpus table now holds the subdirectory name, if present, for each of the three TEI, etc. It finds the ANNIS directory if its name contains 'ANNIS'. This is deployed on the test server.

**Comment by amir-zeldes** [comment]
Yes, looks good - thanks Dave!
