### ISSUE TITLE
Link Text / Text Index templating with SearchTools Controller

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#9]

**Comment by lukehollis** [comment]
Now a user can navigate between the collection list and the single document view without a page refresh.  This is a similar issue to the client-side routing ticket: https://github.com/CopticScriptorium/cts/issues/13

**Comment by ctschroeder** [comment]
? not sure what this is

**Comment by lukehollis** [comment]
This was a development specific ticket that I was using to track the progress on the implementation of the URN resolver with some client-side features in the Angular application.  This one is ready to be closed.
