### ISSUE TITLE
Add the "next", "previous", and "endnote" metadata to visualizations

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#97]
"next" and "previous" should be links.  "endnote" should be texts.  This needs coordination with @amir-zeldes re ANNIS.

One corpus that has these annotations is shenoute.a22

**Comment by amir-zeldes** [comment]
Yes, I think this should work fine. Since the values of the metadata are URNs, this doesn't depend on ANNIS so much as the metadata just needs to be included for this to work. We can test on A22 for now, and once we're satisfied, add the metadatum to all source files that don't have it and reconvert.

The cts repo should not require them though: if a corpus has this metadatum, create a hyperlink based on the URN, otherwise, just don't create it. 

It may also be prudent to alert us with a warning on ingestion if a document has a next/previous URN for which the target does not exist (since in mid import, this can temporarily be the case, the check should only urn once metadata import is complete for the entire corpus).

**Comment by ctschroeder** [comment]
Clarification:  only values of "next" and "previous" are URNs.  Endnote is text.

So: The cts repo should not require them though: if a corpus has **a next or a previous** metadatum, create a hyperlink based on the URN, otherwise, just don't create it.

Warning is fine with me as long as it's not too complicated/resource intensive (in terms of development time).

**Comment by amir-zeldes** [comment]
Yes, if a warning is resource intensive, let's discuss. I think it's pretty important to do it on import though, since we're bound to make out of date URNs that get updated in the URN field, but are forgotten in the next/prev field. The warning would only be issued once ingesting is done for a corpus, there's no need to check it each time a document is loaded up by the search function.

**Comment by ctschroeder** [comment]
Carrie will ask team about positioning of endnote information and will get back to you all.

**Comment by ctschroeder** [comment]
General agreement that endnote contents should be on the screen (not behind a button), and offset by being a smaller font or italics (or both) and centered.

**Comment by dcbriccetti** [comment]
Like this? It’s a smaller font and centered here.
![screen shot 2016-05-26 at 12 34 38 pm](https://cloud.githubusercontent.com/assets/55099/15587503/5aaeaf62-233e-11e6-866f-2f02d2439d0e.png)

**Comment by amir-zeldes** [comment]
I like it but I'd say align left, it's weird for me to read running text over multiple lines centered. @ctschroeder ?

**Comment by dcbriccetti** [comment]
What did you decide about Next/Prev? Were there to be buttons? I don’t remember. Below, any metadatum whose value starts with urn:cts has that value changed into a link.

![screen shot 2016-05-26 at 12 59 51 pm](https://cloud.githubusercontent.com/assets/55099/15588269/da294268-2341-11e6-9ff4-9435d65972ba.png)

**Comment by dcbriccetti** [comment]
Running on test server now. http://52.39.198.200/

**Comment by amir-zeldes** [comment]
Almost perfect - the minor problem I get is when clicking on one of the URN links, I get to a page with that search result at the top, but my browser is auto-scrolled way down to the bottom for some reason - I need to manually scroll up to actually see the document I clicked the URN for. 

As for next/prev, my preference would be a link saying 'next'/'previous' styled via css to look like a button.

**Comment by dcbriccetti** [comment]
Something like this is easy enough (see bottom).

![screen shot 2016-05-26 at 6 58 57 pm](https://cloud.githubusercontent.com/assets/55099/15595445/fb28eb6c-2373-11e6-9740-35848a236931.png)

**Comment by amir-zeldes** [comment]
I'm happy with this, though I'd make them flush left (in fact, there are three different indentations for the buttons in the image above, which looks a bit off aesthetically)

**Comment by ctschroeder** [comment]
This is looking great.  A couple things:
1. I agree with Amir about the flush left
2. When I filter for Besa's corpus and click on the title for On Lack of Food I get this:
<img width="1200" alt="screen shot 2016-05-31 at 10 09 02 am" src="https://cloud.githubusercontent.com/assets/4079217/15683595/0c10dc80-2718-11e6-9b17-a5ea18971cf4.png">
But when I click on "next" I get this screen (url is http://52.39.198.200/urn:cts:copticLit:besa.thieving.monbba):
<img width="1193" alt="screen shot 2016-05-31 at 10 12 04 am" src="https://cloud.githubusercontent.com/assets/4079217/15683633/3526d3cc-2718-11e6-926d-11fcefc6b93b.png">
but I think it would be more efficient to go straight to this screen:
<img width="1187" alt="screen shot 2016-05-31 at 10 13 32 am" src="https://cloud.githubusercontent.com/assets/4079217/15683672/61435d54-2718-11e6-8f71-087424eaf4ef.png">
(which is at http://52.39.198.200/texts/besa_letters/to_thieving_nuns)
Because this latter screen has the same information -- and more!-- than the previous one. Is there some way to direct the previous/next urls to the fuller visualization of information?
3. There is a metadata error in the Besa corpus I'm noticing (leading one of the buttons to send us to a nonexistent page.) This is a problem on my end that I'll fix.

**Comment by ctschroeder** [comment]
Clarifying the above:  I'm asking whether http://52.39.198.200/urn:cts:copticLit:besa.thieving.monbba could resolve to the screen with more information, rather than the basic list item.  If it's not possible  or too complicated, it's ok.  This is looking great.

**Comment by dcbriccetti** [comment]
I’m guessing 1–3 hours for that.

**Comment by ctschroeder** [comment]
Sounds good. Please also send me an invoice for May. Thanks so much!!

**Comment by dcbriccetti** [comment]
Can we solve this in a more general way, by saying that should a urn resolve to a single text, then we go right to that text?

**Comment by ctschroeder** [comment]
YES. If by "text" you mean the page w/all the document metadata+ buttons to viz and downloads.

**Comment by dcbriccetti** [comment]
Yes. I did that and it works nicely. I recommend moving the prev/next buttons up with the others, because once you select a visualization, the prev/next move out of reach below the visualization, making quick lateral navigation harder.

**Comment by ctschroeder** [comment]
Ok, that is fine -- previous/next up top (but UNDER the other buttons), endnote comments below.
Also I'm assuming when you say "I did that" you mean on your own machine and not on the test server, because http://52.39.198.200/urn:cts:copticLit:besa.thieving.monbba still resolves to the single list item.

**Comment by ctschroeder** [comment]
Also it looks like the relANNIS button is missing on some (all?) corpora.  (All the download buttons currently go to the same place, anyway, but it shows people what there is to download, and we may change it later.)  Is the link missing in our database setup or is the button missing in the interface code?  For example, relANNIS is missing in here http://52.39.198.200/urn:cts:copticLit:besa.thieving.monbba.  (hope this makes sense.)

**Comment by dcbriccetti** [comment]
> All the download buttons currently go to the same place, anyway

Ah, but they don’t since you’ve been away. I implemented the feature to go all the way in, and to not show the button if when the corpora was last saved from the admin GUI, that directory was not present on github.

**Comment by dcbriccetti** [comment]
> Also I'm assuming when you say "I did that"

All new changes are on the test server now, and [here’s an example](http://52.39.198.200/filter/author=Besa&annotation=Caroline%20T.%20Schroeder&annotation=Amir%20Zeldes) of a stable URL, without the IDs.

I’ll be out for the next few hours.

**Comment by ctschroeder** [comment]
> Ah, but they don’t since you’ve been away. I implemented the feature to go all the way in, and to not show the button if when the corpora was last saved from the admin GUI, that directory was not present on github.

Oh, ok, thanks.  So you're saying that if I don't see the button, it's because the directory is not on Github?

Unfortunately, the [example URL] (http://52.39.198.200/filter/author=Besa&annotation=Caroline%20T.%20Schroeder&annotation=Amir%20Zeldes) doesn't work.  I get the message that nothing matches my search criteria.

**Comment by amir-zeldes** [comment]
The missing relANNIS is likely because those directories are now called xyz_ANNIS, not xyz_relANNIS - that indicates that their format is relANNIS 3.3 and not 3.2 (it's been a new convention since ANNIS 3.3). Basically any directory of depth 1 in that repo that has ANNIS in it's name is the one you're looking for:

https://github.com/CopticScriptorium/corpora/tree/master/besa-letters

**Comment by dcbriccetti** [comment]
> (Amir, by email) Can you pass the selected visualization information to the next page and display that if available?

Done, and running on test system.
