### ISSUE TITLE
Increase metadata field size to 500 chars

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/cts#98]
The current limit of a metadatum value is 200 chars. This cuts off the 'endnote' field, e.g. in Besa/To Aphthonia: 

```
To Aphtonia is currently the first digitized letter of Besa in the corpus. In the manuscript tradition, there are at least twelve other known letters or fragments before this one, and at least one a
```

The field is cut off at 200 characters. Extending to 500 chars should be enough.

**Comment by dcbriccetti** [comment]
500 was inadequate, so is now 10,000.
