### ISSUE TITLE
Disappearing navigation buttons

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/cts#99]
The navigation buttons (visualization buttons and format links) at the top of the selected document can disappear. To reproduce (possibly other routes are possible):

Select besa.letters
Select To Aphthonia (dipl)
Hit enter in the URL box of the browser

![capture](https://cloud.githubusercontent.com/assets/2188635/14965458/92c12ea0-107b-11e6-9e6e-866d2ba5296d.PNG)

Tested on Win 7 64 bits with Chrome and Firefox and Internet Explorer.

**Comment by dcbriccetti** [comment]
Still working on this. It has to do with the fact that reloading the page like that doesn’t go through the usual steps of the single page application, which “prime” the data.

**Comment by dcbriccetti** [comment]
This could take several more hours to fix. Is it really a high priority? In most use cases it won’t appear.

**Comment by amir-zeldes** [comment]
Could we get a cheap fix using a redirect strategy? If you can parse out the correct URL from the invalid URL produced by hitting enter in the URL box, then maybe you could just recognize this situation and auto navigate to the URL kind that the application likes. Does that make sense?

**Comment by dcbriccetti** [comment]
Good thinking, Amir, but the URL is already correct. There’s nothing different to redirect to.

**Comment by amir-zeldes** [comment]
I see... What I meant was the difference between this URL:

```
http://data.copticscriptorium.org/texts/besa_letters/to_aphthonia/norm
```

and this one, which we give below each document as a reference URL:

```
http://data.copticscriptorium.org/urn:cts:copticLit:besa.aphthonia.monbba/norm/html
```

But sadly, I just tested this and discovered that the latter URL, when opened cold (not from within the interface), also creates the button bug. This means that we have no way of correctly linking to a document visualization from outside the interface. Is that right?

**Comment by dcbriccetti** [comment]
I think I have fixed this. Just testing a bit more.

**Comment by dcbriccetti** [comment]
Running on test server now. http://52.39.198.200/
